/* NNC Runtime Operator Interface
 * Pure operator library - users are responsible for memory management and scheduling.
 *
 * Auto-generated by NNC - DO NOT EDIT
 */

#ifndef NNC_OPS_H
#define NNC_OPS_H

#include "nnc_types.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Arithmetic Operations
 * ============================================================================ */

void nnc_add(Tensor* a, Tensor* b, Tensor* out);
void nnc_mul(Tensor* a, Tensor* b, Tensor* out);
void nnc_sub(Tensor* a, Tensor* b, Tensor* out);
void nnc_div(Tensor* a, Tensor* b, Tensor* out);

/* ============================================================================
 * Neural Network Operations
 * ============================================================================ */

/* 2D Convolution
 * Args:
 *   input:     Input tensor [N, C_in, H, W]
 *   weight:    Weight tensor [C_out, C_in, kH, kW]
 *   bias:      Bias tensor [C_out] (can be NULL)
 *   output:    Output tensor [N, C_out, H_out, W_out]
 *   kernel_h:  Kernel height
 *   kernel_w:  Kernel width
 *   stride_h:  Stride height
 *   stride_w:  Stride width
 *   pad_h:     Padding height (top, bottom)
 *   pad_w:     Padding width (left, right)
 */
void nnc_conv(
    Tensor* input, Tensor* weight, Tensor* bias, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
);

/* Activation functions */
void nnc_relu(Tensor* input, Tensor* output);
void nnc_sigmoid(Tensor* input, Tensor* output);
void nnc_tanh(Tensor* input, Tensor* output);
void nnc_softmax(Tensor* input, Tensor* output, int axis);

/* ============================================================================
 * Pooling Operations
 * ============================================================================ */

/* 2D Max Pooling
 * Args:
 *   input:    Input tensor [N, C, H, W]
 *   output:   Output tensor
 *   kernel_h: Kernel height
 *   kernel_w: Kernel width
 *   stride_h: Stride height
 *   stride_w: Stride width
 *   pad_h:    Padding height
 *   pad_w:    Padding width
 */
void nnc_maxpool2d(
    Tensor* input, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
);

/* 2D Average Pooling */
void nnc_avgpool2d(
    Tensor* input, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
);

/* ============================================================================
 * Shape Manipulation Operations
 * ============================================================================ */

void nnc_reshape(Tensor* input, Tensor* output, int64_t* shape, int ndim);
void nnc_flatten(Tensor* input, Tensor* output, int axis);
void nnc_transpose(Tensor* input, Tensor* output, int64_t* perm, int ndim);
void nnc_squeeze(Tensor* input, Tensor* output, int axis);
void nnc_unsqueeze(Tensor* input, Tensor* output, int axis);

/* ============================================================================
 * Matrix Operations
 * ============================================================================ */

void nnc_matmul(Tensor* a, Tensor* b, Tensor* output);
void nnc_gemm(
    Tensor* a, Tensor* b, Tensor* c, Tensor* output,
    float alpha, float beta, int trans_a, int trans_b
);

/* ============================================================================
 * Reduction Operations
 * ============================================================================ */

void nnc_reducemean(Tensor* input, Tensor* output, int axis, int keepdims);
void nnc_reducesum(Tensor* input, Tensor* output, int axis, int keepdims);

/* ============================================================================
 * Other Operations
 * ============================================================================ */

void nnc_concat(Tensor** inputs, Tensor* output, int num_inputs, int axis);
void nnc_batchnorm(
    Tensor* input, Tensor* scale, Tensor* bias, Tensor* mean, Tensor* var,
    Tensor* output, float epsilon, int momentum
);

/* Layer Normalization
 * Args:
 *   input:   Input tensor
 *   scale:   Scale (gamma) tensor - can be NULL
 *   bias:    Bias (beta) tensor - can be NULL
 *   output:  Output tensor
 *   axis:    Normalization axis (-1 for last dimension)
 *   epsilon: Small constant for numerical stability
 */
void nnc_layernorm(
    Tensor* input, Tensor* scale, Tensor* bias, Tensor* output,
    int axis, float epsilon
);

void nnc_clip(Tensor* input, Tensor* output, float min_val, float max_val);

#ifdef __cplusplus
}
#endif

#endif  // NNC_OPS_H
