/* NNC Runtime Type Definitions
 * Auto-generated by NNC - DO NOT EDIT
 */

#ifndef NNC_TYPES_H
#define NNC_TYPES_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Data type enumeration */
typedef enum {
    NNC_DTYPE_FLOAT32 = 0,
    NNC_DTYPE_FLOAT16 = 1,
    NNC_DTYPE_INT32 = 2,
    NNC_DTYPE_INT8 = 3,
    NNC_DTYPE_UINT8 = 4,
    NNC_DTYPE_BOOL = 5,
} nnc_dtype_t;

/* Tensor structure */
typedef struct {
    void* data;           /* Data pointer */
    nnc_dtype_t dtype;    /* Data type */
    int64_t* shape;       /* Shape array */
    int ndim;             /* Number of dimensions */
    int64_t nbytes;       /* Total bytes */
} Tensor;

#ifdef __cplusplus
}
#endif

#endif  // NNC_TYPES_H
