/* NNC Runtime Interface
 * Memory management and scheduling - users are responsible for implementation.
 *
 * Auto-generated by NNC - DO NOT EDIT
 */

#ifndef NNC_RUNTIME_H
#define NNC_RUNTIME_H

#include "nnc_types.h"
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Memory Management (to be implemented by user)
 * ============================================================================ */

/* Allocate memory for a tensor */
void* nnc_alloc_tensor(size_t nbytes);

/* Free tensor memory */
void nnc_free_tensor(void* ptr);

/* NPU-specific memory allocation (if needed) */
void* nnc_alloc_npu_memory(size_t nbytes);
void nnc_free_npu_memory(void* ptr);

/* ============================================================================
 * Scheduler Interface (to be implemented by user)
 * ============================================================================ */

/* Initialize the scheduler */
void nnc_scheduler_init(void);

/* Submit a computation task */
void nnc_schedule_task(void (*task)(void), void* args);

/* Wait for all tasks to complete */
void nnc_wait_all(void);

#ifdef __cplusplus
}
#endif

#endif  // NNC_RUNTIME_H
