/* NNC Runtime Operator Interface
 * Pure operator library - users are responsible for memory management and scheduling.
 *
 * Auto-generated by NNC - DO NOT EDIT
 */

#ifndef NNC_OPS_H
#define NNC_OPS_H

#include "nnc_types.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Arithmetic Operations
 * ============================================================================ */

void nnc_add(Tensor* a, Tensor* b, Tensor* out);
void nnc_mul(Tensor* a, Tensor* b, Tensor* out);
void nnc_sub(Tensor* a, Tensor* b, Tensor* out);
void nnc_div(Tensor* a, Tensor* b, Tensor* out);

/* ============================================================================
 * Comparison Operations
 * ============================================================================ */

/* Equal - element-wise equality comparison
 * Args:
 *   a: First input tensor
 *   b: Second input tensor
 *   out: Output tensor (1.0f where a == b, 0.0f otherwise)
 */
void nnc_equal(Tensor* a, Tensor* b, Tensor* out);

/* And - element-wise logical AND
 * Args:
 *   a: First input tensor
 *   b: Second input tensor
 *   out: Output tensor (1.0f where both a and b are non-zero, 0.0f otherwise)
 */
void nnc_and(Tensor* a, Tensor* b, Tensor* out);

/* ============================================================================
 * Neural Network Operations
 * ============================================================================ */

/* 2D Convolution
 * Args:
 *   input:     Input tensor [N, C_in, H, W]
 *   weight:    Weight tensor [C_out, C_in, kH, kW]
 *   bias:      Bias tensor [C_out] (can be NULL)
 *   output:    Output tensor [N, C_out, H_out, W_out]
 *   kernel_h:  Kernel height
 *   kernel_w:  Kernel width
 *   stride_h:  Stride height
 *   stride_w:  Stride width
 *   pad_h:     Padding height (top, bottom)
 *   pad_w:     Padding width (left, right)
 */
void nnc_conv(
    Tensor* input, Tensor* weight, Tensor* bias, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
);

/* Activation functions */
void nnc_relu(Tensor* input, Tensor* output);
void nnc_sigmoid(Tensor* input, Tensor* output);
void nnc_tanh(Tensor* input, Tensor* output);
void nnc_softmax(Tensor* input, Tensor* output, int axis);

/* ============================================================================
 * Math Operations (Unary Element-wise)
 * ============================================================================ */

/* Sqrt - element-wise square root
 * Args:
 *   input:  Input tensor
 *   output: Output tensor (sqrt(x) for each element)
 */
void nnc_sqrt(Tensor* input, Tensor* output);

/* Exp - element-wise exponential
 * Args:
 *   input:  Input tensor
 *   output: Output tensor (exp(x) for each element)
 */
void nnc_exp(Tensor* input, Tensor* output);

/* Log - element-wise natural logarithm
 * Args:
 *   input:  Input tensor
 *   output: Output tensor (log(x) for each element)
 */
void nnc_log(Tensor* input, Tensor* output);

/* Abs - element-wise absolute value
 * Args:
 *   input:  Input tensor
 *   output: Output tensor (|x| for each element)
 */
void nnc_abs(Tensor* input, Tensor* output);

/* Neg - element-wise negation
 * Args:
 *   input:  Input tensor
 *   output: Output tensor (-x for each element)
 */
void nnc_neg(Tensor* input, Tensor* output);

/* ============================================================================
 * Pooling Operations
 * ============================================================================ */

/* 2D Max Pooling
 * Args:
 *   input:    Input tensor [N, C, H, W]
 *   output:   Output tensor
 *   kernel_h: Kernel height
 *   kernel_w: Kernel width
 *   stride_h: Stride height
 *   stride_w: Stride width
 *   pad_h:    Padding height
 *   pad_w:    Padding width
 */
void nnc_maxpool2d(
    Tensor* input, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
);

/* 2D Average Pooling */
void nnc_avgpool2d(
    Tensor* input, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
);

/* ============================================================================
 * Shape Manipulation Operations
 * ============================================================================ */

void nnc_reshape(Tensor* input, Tensor* output, int64_t* shape, int ndim);
void nnc_flatten(Tensor* input, Tensor* output, int axis);
void nnc_transpose(Tensor* input, Tensor* output, int64_t* perm, int ndim);
void nnc_squeeze(Tensor* input, Tensor* output, int axis);
void nnc_unsqueeze(Tensor* input, Tensor* output, int axis);

/* Tile operation - repeats input tensor along each axis
 * Args:
 *   input:   Input tensor
 *   output:  Output tensor
 *   repeats: Array specifying repeat count for each axis (can be NULL)
 *   ndim:    Number of dimensions in repeats array
 */
void nnc_tile(Tensor* input, Tensor* output, int64_t* repeats, int ndim);

/* ============================================================================
 * Matrix Operations
 * ============================================================================ */

void nnc_matmul(Tensor* a, Tensor* b, Tensor* output);
void nnc_gemm(
    Tensor* a, Tensor* b, Tensor* c, Tensor* output,
    float alpha, float beta, int trans_a, int trans_b
);

/* ============================================================================
 * Reduction Operations
 * ============================================================================ */

void nnc_reducemean(Tensor* input, Tensor* output, int axis, int keepdims);
void nnc_reducesum(Tensor* input, Tensor* output, int axis, int keepdims);

/* ============================================================================
 * Other Operations
 * ============================================================================ */

void nnc_concat(Tensor** inputs, Tensor* output, int num_inputs, int axis);
void nnc_batchnorm(
    Tensor* input, Tensor* scale, Tensor* bias, Tensor* mean, Tensor* var,
    Tensor* output, float epsilon, int momentum
);

/* Layer Normalization
 * Args:
 *   input:   Input tensor
 *   scale:   Scale (gamma) tensor - can be NULL
 *   bias:    Bias (beta) tensor - can be NULL
 *   output:  Output tensor
 *   axis:    Normalization axis (-1 for last dimension)
 *   epsilon: Small constant for numerical stability
 */
void nnc_layernorm(
    Tensor* input, Tensor* scale, Tensor* bias, Tensor* output,
    int axis, float epsilon
);

/* Identity operation - copies input to output */
void nnc_identity(Tensor* input, Tensor* output);

/* Split operation - divides tensor along axis into multiple outputs
 * Args:
 *   input:      Input tensor to split
 *   outputs:    Array of output tensors
 *   num_outputs: Number of output tensors
 *   axis:       Axis along which to split
 */
void nnc_split(Tensor* input, Tensor** outputs, int num_outputs, int axis);

void nnc_clip(Tensor* input, Tensor* output, float min_val, float max_val);

#ifdef __cplusplus
}
#endif

#endif  // NNC_OPS_H
