"""Build artifact emitters for x86 codegen packages."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from nnc_py.codegen.x86_ir import X86CodegenPackage


def _default_runtime_dir() -> str:
    """Return the default runtime directory to embed into generated builds."""
    # build_files.py lives at src/nnc_py/codegen/x86_emitters/build_files.py
    # parents: [0]=x86_emitters, [1]=codegen, [2]=nnc_py, [3]=src, [4]=project root
    runtime_dir = Path(__file__).resolve().parents[4] / "runtime"
    return str(runtime_dir)


def _get_scheduled_memory_plan(ctx: Any) -> Any | None:
    plan = ctx.metadata.get("scheduled_memory_plan")
    if plan is None:
        return None
    if not hasattr(plan, "fast_allocations") or not hasattr(plan, "transfer_points"):
        return None
    return plan


def _prefer_scheduled_memory_plan(ctx: Any, scheduled_plan: Any | None = None) -> bool:
    if scheduled_plan is None:
        scheduled_plan = _get_scheduled_memory_plan(ctx)
    return (
        scheduled_plan is not None
        and ctx.optimization_level >= 3
        and bool(ctx.metadata.get("pipeline_scheduler_enabled"))
    )


def emit_makefile(package: X86CodegenPackage) -> str:
    """Emit the build Makefile from a lowered package."""
    ctx = package.ctx
    has_constants = bool(ctx.graph.constants)
    objs = "model.o tensors.o"
    if has_constants:
        objs += " constants_loader.o"
    objs += " test_runner.o ops.o"
    runtime_dir = _default_runtime_dir()

    makefile_body = f"""# Auto-generated by NNC - DO NOT EDIT
# Set NNC_RUNTIME_PATH to point to the runtime directory if not in dev tree
# Set NNC_RUNTIME_IMPL=costmodel to link the timing-model runtime instead of real kernels
CC = gcc
CFLAGS = -D_GNU_SOURCE -std=c11 -O2 -Wall -Wextra -pthread
LDFLAGS = -lm -pthread

# Runtime include path - can be overridden by environment
NNC_RUNTIME ?= {runtime_dir}
NNC_RUNTIME_IMPL ?= ops
CFLAGS += -I$(NNC_RUNTIME)/include

.PHONY: all clean run

all: model

model: {objs}
\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

ops.o:
\t$(CC) $(CFLAGS) -c $(NNC_RUNTIME)/x86/$(NNC_RUNTIME_IMPL).c -o $@

%.o: %.c
\t$(CC) $(CFLAGS) -c $<

clean:
\trm -f *.o model

run: model
\t./model

run-costmodel:
\t$(MAKE) clean
\t$(MAKE) NNC_RUNTIME_IMPL=costmodel run
"""

    return makefile_body


def emit_test_runner(package: X86CodegenPackage, debug_mode: bool = False) -> str:
    """Emit the x86 test runner from a lowered package."""
    ctx = package.ctx
    scheduled_plan = _get_scheduled_memory_plan(ctx)
    static_storage_mode = (
        _prefer_scheduled_memory_plan(ctx, scheduled_plan)
        or ctx.metadata.get("memory_allocation_plan") is not None
        or "memory_plan" in ctx.metadata
    )

    # Debug mode: add file setup for debug output
    debug_decl = ""
    debug_setup = ""
    debug_cleanup = ""
    debug_macros = ""
    if debug_mode:
        # Declare debug_file as a global variable (extern declaration in model.c)
        debug_decl = """
/* Global debug file pointer (also declared as extern in model.c) */
FILE* debug_file = NULL;
"""
        debug_setup = """
    /* Open debug output file */
    debug_file = fopen("nnc_debug_output.txt", "w");
    if (!debug_file) {
        fprintf(stderr, "Failed to open debug output file\\n");
        return 1;
    }
"""
        debug_cleanup = """
    /* Close debug output file */
    if (debug_file) {
        fclose(debug_file);
        debug_file = NULL;
    }
    printf("Debug output written to nnc_debug_output.txt\\n");"""
        # Define macros to redirect debug printf to file
        debug_macros = """
/* Debug mode: redirect debug output to file */
#define DEBUG_PRINTF(fmt, ...) fprintf(debug_file, fmt, ##__VA_ARGS__)
#define DEBUG_PRINT_TENSOR_START(name, idx) DEBUG_PRINTF("DEBUG_TENSOR_START %s %d\\n", name, idx)
#define DEBUG_PRINT_SHAPE(ndim) DEBUG_PRINTF("SHAPE %d\\n", ndim)
#define DEBUG_PRINT_DIM(i, val) DEBUG_PRINTF("DIM %d %d\\n", i, val)
#define DEBUG_PRINT_DATA_START() DEBUG_PRINTF("DATA_START\\n")
#define DEBUG_PRINT_VALUE(val) DEBUG_PRINTF("%f\\n", val)
#define DEBUG_PRINT_DATA_END() DEBUG_PRINTF("DATA_END\\n")
#define DEBUG_PRINT_TENSOR_END(name) DEBUG_PRINTF("DEBUG_TENSOR_END %s\\n\\n", name)
"""

    # Generate tensor setup code
    tensor_setups = []

    if static_storage_mode:
        # Static allocation - memory is pre-allocated in memory pool
        # Only need to initialize input tensors with test data
        static_bytes = 0
        if _prefer_scheduled_memory_plan(ctx, scheduled_plan) and scheduled_plan is not None:
            static_bytes = int(getattr(scheduled_plan, "total_fast_memory", 0))
        elif ctx.metadata.get("memory_allocation_plan") is not None:
            alloc_plan = ctx.metadata["memory_allocation_plan"]
            static_bytes = int(getattr(alloc_plan, "total_fast_memory", 0))
        else:
            from nnc_py.passes.memory_plan import get_memory_plan
            plan = get_memory_plan(ctx)
            static_bytes = int(getattr(plan, "total_size", 0))

        tensor_setups.append(f"    /* Using static memory pool: {static_bytes} bytes */")
        tensor_setups.append("")

        # Setup input tensors - only initialize with test data
        for tensor_name in ctx.graph.inputs:
            tensor = ctx.graph.get_tensor(tensor_name)
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            size = tensor.byte_size()

            tensor_setups.append(f"    /* Initialize {var_name} */")

            # Initialize with test pattern
            num_elements = size // 4
            tensor_setups.append(f"    for (int i = 0; i < {num_elements}; i++) {{")
            tensor_setups.append(f"        ((float*){var_name}.data)[i] = (float)i * 0.01f;  /* Test pattern */")
            tensor_setups.append(f"    }}")
            tensor_setups.append("")
    else:
        # Dynamic allocation - use malloc/calloc
        # Setup input tensors
        for tensor_name in ctx.graph.inputs:
            tensor = ctx.graph.get_tensor(tensor_name)
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            size = tensor.byte_size()

            # Generate shape array
            shape_list = tensor.shape.dims
            # Handle symbolic dimensions (strings) by converting to -1
            shape_init = ", ".join(str(d) if isinstance(d, (int, float)) else "-1" for d in shape_list)

            # Setup code
            tensor_setups.append(f"    /* Setup {var_name} */")
            tensor_setups.append(f"    static int64_t {var_name}_shape[] = {{{shape_init}}};")
            tensor_setups.append(f"    {var_name}.shape = {var_name}_shape;")
            tensor_setups.append(f"    {var_name}.ndim = {len(shape_list)};")
            tensor_setups.append(f"    {var_name}.dtype = NNC_DTYPE_FLOAT32;")
            tensor_setups.append(f"    {var_name}.nbytes = {size};")
            tensor_setups.append(f"    {var_name}.data = malloc({size});")
            tensor_setups.append(f"    if (!{var_name}.data) {{ fprintf(stderr, \"Failed to allocate {var_name}\\\\n\"); return 1; }}")

            # Initialize with test pattern
            num_elements = size // 4
            tensor_setups.append(f"    for (int i = 0; i < {num_elements}; i++) {{")
            tensor_setups.append(f"        ((float*){var_name}.data)[i] = (float)i * 0.01f;  /* Test pattern */")
            tensor_setups.append(f"    }}")
            tensor_setups.append("")

        # Setup intermediate and output tensors
        for tensor_name, tensor in ctx.graph.tensors.items():
            if tensor_name in ctx.graph.inputs or tensor_name in ctx.graph.constants:
                continue

            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            size = tensor.byte_size()
            shape_list = tensor.shape.dims
            # Handle symbolic dimensions (strings) by converting to -1
            shape_init = ", ".join(str(d) if isinstance(d, (int, float)) else "-1" for d in shape_list)

            tensor_setups.append(f"    /* Setup {var_name} */")
            tensor_setups.append(f"    static int64_t {var_name}_shape[] = {{{shape_init}}};")
            tensor_setups.append(f"    {var_name}.shape = {var_name}_shape;")
            tensor_setups.append(f"    {var_name}.ndim = {len(shape_list)};")
            tensor_setups.append(f"    {var_name}.dtype = NNC_DTYPE_FLOAT32;")
            tensor_setups.append(f"    {var_name}.nbytes = {size};")
            tensor_setups.append(f"    {var_name}.data = calloc({size // 4}, sizeof(float));  /* Initialize to zero */")
            tensor_setups.append(f"    if (!{var_name}.data) {{ fprintf(stderr, \"Failed to allocate {var_name}\\\\n\"); return 1; }}")
            tensor_setups.append("")

    setup_code = "\n".join(tensor_setups)

    # Free memory - only for dynamic allocation
    if static_storage_mode:
        frees_code = "    /* Static allocation - no free needed */"
    else:
        tensor_frees = []
        for tensor_name in ctx.graph.tensors:
            if tensor_name in ctx.graph.constants:
                continue
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            tensor_frees.append(f"    free({var_name}.data);")
        frees_code = "\n".join(tensor_frees)

    # Get input and output tensor variable names
    input_var = None
    if ctx.graph.inputs:
        input_name = ctx.graph.inputs[0]
        input_var = ctx.tensor_symbols.get(input_name, input_name)

    output_var = None
    if ctx.graph.outputs:
        output_name = ctx.graph.outputs[0]
        output_var = ctx.tensor_symbols.get(output_name, output_name)

    # Generate print code only if we have input/output tensors
    print_code = ""

    # Add constants loading code if there are constants
    has_constants = bool(ctx.graph.constants)
    if has_constants:
        constants_load_code = """
    /* Load constants from binary file */
    printf("Loading constants from constants.bin...\\n");
    if (nnc_load_constants("constants.bin") != 0) {
        fprintf(stderr, "Failed to load constants\\n");
        return 1;
    }
    printf("Constants loaded successfully.\\n");"""
    else:
        constants_load_code = ""

    if input_var and output_var:
        print_code = f"""
{constants_load_code}
    /* Print input info */
    printf("Input data (first 10):\\n");
    int64_t input_size = 1;
    for (int i = 0; i < {input_var}.ndim; i++) {{
        input_size *= {input_var}.shape[i];
    }}
    for (int i = 0; i < 10 && i < input_size; i++) {{
        printf("  input[%d] = %f\\n", i, ((float*){input_var}.data)[i]);
    }}

    /* Run inference */
    printf("\\nRunning inference...\\n");
    nnc_run();

    /* Print output results */
    printf("\\nOutput results (first 10):\\n");
    int64_t output_size = 1;
    for (int i = 0; i < {output_var}.ndim; i++) {{
        output_size *= {output_var}.shape[i];
    }}
    for (int i = 0; i < 10 && i < output_size; i++) {{
        printf("  output[%d] = %f\\n", i, ((float*){output_var}.data)[i]);
    }}"""
    else:
        if constants_load_code:
            print_code = f"""
{constants_load_code}

    /* Run inference */
    printf("Running inference...\\n");
    nnc_run();"""
        else:
            print_code = """
    /* Run inference */
    printf("Running inference...\\n");
    nnc_run();"""

    return f"""/* Auto-generated by NNC - DO NOT EDIT */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "nnc_types.h"
#include "model.h"
{debug_macros}
{debug_decl}
int main(void) {{
    printf("NNC Model Runner\\n");
    printf("================\\n");
{debug_setup}
    /* Setup all tensors */
{setup_code}
{print_code}

    /* Free memory */
{frees_code}
{debug_cleanup}
    printf("\\nInference complete.\\n");
    return 0;
}}
"""
