"""Header emitter for x86 codegen packages."""

from __future__ import annotations

import numpy as np

from nnc_py.codegen.x86_ir import X86CodegenPackage


def _get_public_entry_point(ctx: "CompileContext") -> str:  # noqa: F821
    """Get the public entry-point symbol name for generated code."""
    entry_point = ctx.metadata.get("entry_point", "nnc_run")
    if not isinstance(entry_point, str) or not entry_point:
        return "nnc_run"
    return entry_point


def emit_header(package: X86CodegenPackage) -> str:
    """Emit the x86 public header from a lowered package."""
    if package.ctx is None:
        # Minimal stub when no compile context is available
        lines = [
            "/* Auto-generated by NNC - DO NOT EDIT */",
            "#pragma once",
            "",
            "void nnc_run(void);",
        ]
        if package.entry_point != "nnc_run":
            lines.append(f"void {package.entry_point}(void);")
        lines.append("")
        return "\n".join(lines)

    ctx = package.ctx
    lines = [
        "/* Auto-generated by NTC - DO NOT EDIT */",
        "#ifndef MODEL_H",
        "#define MODEL_H",
        "",
        "#include <stdint.h>",
        '#include "nnc_types.h"',
        "",
        "/* Tensor declarations */",
    ]

    # Declare all non-constant tensors
    for tensor_name in ctx.graph.inputs:
        var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
        lines.append(f"extern Tensor {var_name};")

    for tensor_name, tensor in ctx.graph.tensors.items():
        if tensor_name in ctx.graph.inputs or tensor_name in ctx.graph.constants:
            continue
        var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
        lines.append(f"extern Tensor {var_name};")

    for tensor_name in ctx.graph.outputs:
        var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
        if f"extern Tensor {var_name};" not in lines:
            lines.append(f"extern Tensor {var_name};")

    # Declare constant tensors (defined in constants_loader.c)
    for tensor_name in ctx.graph.constants:
        var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
        if f"extern Tensor {var_name};" not in lines:
            lines.append(f"extern Tensor {var_name};")

    # Declare constant data arrays for use in shape operations
    for tensor_name, arr in ctx.graph.constants.items():
        # Only declare INT64 arrays (used for shapes)
        if arr.dtype == np.int64 or arr.dtype == np.int32:
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            dtype = "int64_t" if arr.dtype == np.int64 else "int32_t"
            size = arr.size
            lines.append(f"extern const {dtype} {var_name}_data[{size}];")

    lines.extend([
        "",
        "/* Constants loading function */",
        "int nnc_load_constants(const char* path);",
        "",
        "/* Main inference function */",
        "void nnc_run(void);",
    ])

    entry_point = _get_public_entry_point(ctx)
    if entry_point != "nnc_run":
        lines.extend([
            "",
            "/* Public entry point alias */",
            f"void {entry_point}(void);",
        ])

    lines.extend([
        "",
        "#endif  // MODEL_H",
    ])

    return "\n".join(lines)
