"""Header emitter for x86 codegen packages."""

from __future__ import annotations

from typing import Any

from nnc_py.codegen.x86_ir import X86CodegenPackage


def emit_header(package: X86CodegenPackage, backend: Any | None = None) -> str:
    """Emit the x86 public header from a lowered package."""
    if package.ctx is not None and backend is not None:
        return backend._generate_header(package.ctx)

    lines = [
        "/* Auto-generated by NNC - DO NOT EDIT */",
        "#pragma once",
        "",
        "void nnc_run(void);",
    ]
    if package.entry_point != "nnc_run":
        lines.append(f"void {package.entry_point}(void);")
    lines.append("")
    return "\n".join(lines)
