"""Model source emitter for x86 codegen packages."""

from __future__ import annotations

from typing import Any

from nnc_py.codegen.x86_ir import X86CodegenPackage


def emit_model_source(package: X86CodegenPackage, backend: Any | None = None) -> str:
    """Emit model source from a lowered package."""
    if package.ctx is None or backend is None:
        return _emit_minimal_model_source(package)
    return backend._generate_source(package.ctx)


def _emit_minimal_model_source(package: X86CodegenPackage) -> str:
    lines = [
        "/* Auto-generated by NNC - DO NOT EDIT */",
        "",
        "/* Pipeline schedule summary",
    ]
    for summary_line in package.pipeline_summary_lines:
        lines.append(f" * {summary_line}")
    lines.extend(
        [
            " */",
            "",
            "void nnc_run(void) {",
            "}",
        ]
    )
    if package.entry_point != "nnc_run":
        lines.extend(
            [
                "",
                f"void {package.entry_point}(void) {{",
                "    nnc_run();",
                "}",
            ]
        )
    lines.append("")
    return "\n".join(lines)
