"""Model source emitter for x86 codegen packages."""

from __future__ import annotations

from typing import Any

from nnc_py.codegen.c_emitter import CEmitter
from nnc_py.codegen.x86_ir import X86CodegenPackage
from nnc_py.passes.memory_planning import get_memory_allocation_plan
from nnc_py.passes.spill import get_spill_plan


# ---------------------------------------------------------------------------
# Pure helper functions (migrated from X86Backend)
# ---------------------------------------------------------------------------

def _sanitize_c_comment_text(value: str) -> str:
    """Avoid terminating generated C comments accidentally."""
    return value.replace("*/", "* /").replace("\n", " ")


def _has_parallel_runtime(pipeline_codegen_metadata: dict[str, Any]) -> bool:
    runtime = pipeline_codegen_metadata.get("parallel_runtime")
    return bool(isinstance(runtime, dict) and runtime.get("enabled") is True)


def _get_public_entry_point(ctx: Any) -> str:
    entry_point = ctx.metadata.get("entry_point", "nnc_run")
    if not isinstance(entry_point, str) or not entry_point:
        return "nnc_run"
    return entry_point


# ---------------------------------------------------------------------------
# Main emitter
# ---------------------------------------------------------------------------

def emit_model_source(package: X86CodegenPackage, backend: Any | None = None) -> str:
    """Emit model source from a lowered package."""
    if package.ctx is None or backend is None:
        return _emit_minimal_model_source(package)

    ctx = package.ctx
    alloc_plan = get_memory_allocation_plan(ctx)
    tile_aware_runtime_plan = backend._get_tile_aware_runtime_plan(ctx, alloc_plan)
    scheduled_plan = package.scheduled_plan
    prefer_scheduled_plan = scheduled_plan is not None
    pipeline_codegen_metadata = package.pipeline_codegen_metadata
    spill_plan = get_spill_plan(ctx)

    used_standard_emitter = False
    if (
        prefer_scheduled_plan
        and backend.debug_mode
        and scheduled_plan is not None
        and bool(getattr(scheduled_plan, "transfer_points", ()))
    ):
        source = _emit_scheduled_spill_model_source(
            ctx,
            scheduled_plan,
            pipeline_codegen_metadata,
            backend,
        )
    elif prefer_scheduled_plan:
        emitter = CEmitter(
            tile_aware_wrapper_nodes=tile_aware_runtime_plan.get("wrapper_nodes", {}),
            pipeline_schedule_metadata=pipeline_codegen_metadata,
        )
        source = emitter.emit(ctx)
        used_standard_emitter = True
    elif alloc_plan is not None and (alloc_plan.has_spill or bool(alloc_plan.move_points)):
        source = backend._generate_source_with_unified_spill(
            ctx,
            alloc_plan,
            pipeline_codegen_metadata,
        )
    elif spill_plan is not None and spill_plan.has_overflow:
        source = _emit_legacy_spill_model_source(
            ctx,
            spill_plan,
            pipeline_codegen_metadata,
            backend,
        )
    else:
        emitter = CEmitter(
            tile_aware_wrapper_nodes=tile_aware_runtime_plan.get("wrapper_nodes", {}),
            pipeline_schedule_metadata=pipeline_codegen_metadata,
        )
        source = emitter.emit(ctx)
        used_standard_emitter = True

    if used_standard_emitter:
        source = backend._inject_parallel_runtime_into_emitted_source(
            source,
            pipeline_codegen_metadata,
        )

    source = backend._add_debug_macros(source)
    source = backend._inject_debug_into_nnc_run(source, ctx)
    return backend._append_entry_point_alias(source, ctx)


def _emit_minimal_model_source(package: X86CodegenPackage) -> str:
    lines = [
        "/* Auto-generated by NNC - DO NOT EDIT */",
        "",
        "/* Pipeline schedule summary",
    ]
    for summary_line in package.pipeline_summary_lines:
        lines.append(f" * {summary_line}")
    lines.extend(
        [
            " */",
            "",
            "void nnc_run(void) {",
            "}",
        ]
    )
    if package.entry_point != "nnc_run":
        lines.extend(
            [
                "",
                f"void {package.entry_point}(void) {{",
                "    nnc_run();",
                "}",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def _append_pipeline_schedule_summary_block(
    lines: list[str],
    pipeline_codegen_metadata: dict[str, Any],
    backend: Any | None = None,
) -> None:
    lines.append("/* Pipeline schedule summary")
    for summary_line in pipeline_codegen_metadata.get("summary_lines", ()):
        lines.append(f" * {_sanitize_c_comment_text(str(summary_line))}")
    lines.append(" */")
    lines.append("")


def _append_pipeline_step_comment_lines(
    lines: list[str],
    pipeline_codegen_metadata: dict[str, Any],
    node_name: str,
    *,
    backend: Any | None = None,
    indent: str = "",
) -> None:
    for comment in pipeline_codegen_metadata.get("node_comments", {}).get(node_name, ()):
        lines.append(f"{indent}/* {_sanitize_c_comment_text(comment)} */")


def _emit_scheduled_spill_model_source(
    ctx: Any,
    scheduled_plan: Any,
    pipeline_codegen_metadata: dict[str, Any],
    backend: Any,
) -> str:
    lines = [
        "/* Auto-generated by NNC - DO NOT EDIT */",
        "",
        "#include <stdio.h>",
        "#include <stdlib.h>",
        "#include <string.h>",
        '#include "model.h"',
        '#include "nnc_ops.h"',
        "",
        "/* External memory pools (defined in tensors.c) */",
        "extern uint8_t _nnc_fast_pool[];",
        "extern uint8_t _nnc_slow_pool[];",
        "",
    ]
    _append_pipeline_schedule_summary_block(lines, pipeline_codegen_metadata, backend)

    nodes = ctx.graph.topological_sort()
    for node in nodes:
        if node.op_type.value == "constant":
            continue
        func_name = ctx.node_symbols.get(node.name, node.name)
        lines.append(f"static void {func_name}_body(void);")

    lines.append("")
    lines.append("/* Scheduled spill/reload wrapper functions */")

    for node in nodes:
        if node.op_type.value == "constant":
            continue

        func_name = ctx.node_symbols.get(node.name, node.name)
        reload_points = backend._get_scheduled_transfer_points_for_node(
            scheduled_plan,
            before_node_name=node.name,
            transfer_kind="reload_dma",
        )
        spill_points = backend._get_scheduled_transfer_points_for_node(
            scheduled_plan,
            after_node_name=node.name,
            transfer_kind="spill_dma",
        )

        lines.append(f"/* {func_name}: {node.op_type.value} */")
        lines.append(f"static void {func_name}(void) {{")
        _append_pipeline_step_comment_lines(
            lines,
            pipeline_codegen_metadata,
            node.name,
            backend=backend,
            indent="    ",
        )

        for transfer_point in reload_points:
            for body_line in backend._build_scheduled_transfer_body_lines(ctx, transfer_point):
                lines.append(f"    {body_line}")

        lines.append(f"    {func_name}_body();")

        for transfer_point in spill_points:
            for body_line in backend._build_scheduled_transfer_body_lines(ctx, transfer_point):
                lines.append(f"    {body_line}")

        lines.append("}")
        lines.append("")

    lines.append("/* Node body functions */")
    emitter = CEmitter(pipeline_schedule_metadata=pipeline_codegen_metadata)
    body_code = emitter.emit(ctx)
    lines.append(backend._process_body_code(body_code, ctx))

    lines.append("")
    lines.append("/* Main inference entry point */")
    lines.append("void nnc_run(void) {")
    for node in nodes:
        if node.op_type.value == "constant":
            continue
        func_name = ctx.node_symbols.get(node.name, node.name)
        _append_pipeline_step_comment_lines(
            lines,
            pipeline_codegen_metadata,
            node.name,
            backend=backend,
            indent="    ",
        )
        lines.append(f"    {func_name}();")
    lines.append("}")

    return "\n".join(lines)


def _emit_legacy_spill_model_source(
    ctx: Any,
    spill_plan: Any,
    pipeline_codegen_metadata: dict[str, Any],
    backend: Any,
) -> str:
    pipeline_codegen_metadata = backend._augment_parallel_runtime_for_legacy_spill(
        ctx,
        spill_plan,
        pipeline_codegen_metadata,
    )

    lines = [
        "/* Auto-generated by NNC - DO NOT EDIT */",
        "",
        "#include <stdio.h>",
        "#include <stdlib.h>",
        "#include <string.h>",
        '#include "model.h"',
        '#include "nnc_ops.h"',
        "",
        "/* External memory pools (defined in tensors.c) */",
        "extern uint8_t _nnc_fast_pool[];",
        "extern uint8_t _nnc_slow_pool[];",
        "",
        "/* Forward declarations for spill/reload functions */",
    ]
    backend._append_parallel_runtime_includes(lines, pipeline_codegen_metadata)
    _append_pipeline_schedule_summary_block(lines, pipeline_codegen_metadata, backend)

    nodes = ctx.graph.topological_sort()
    for node in nodes:
        if node.op_type.value == "constant":
            continue
        func_name = ctx.node_symbols.get(node.name, node.name)
        lines.append(f"static void {func_name}_body(void);")

    lines.append("")
    lines.append("/* Spill/Reload wrapper functions */")

    for node in nodes:
        if node.op_type.value == "constant":
            continue

        func_name = ctx.node_symbols.get(node.name, node.name)
        spills_after = [
            point for point in spill_plan.spill_points if point.after_node == node.name
        ]
        reloads_before = [
            point for point in spill_plan.reload_points if point.before_node == node.name
        ]

        lines.append(f"/* {func_name}: {node.op_type.value} */")
        lines.append(f"static void {func_name}(void) {{")
        _append_pipeline_step_comment_lines(
            lines,
            pipeline_codegen_metadata,
            node.name,
            backend=backend,
            indent="    ",
        )

        for reload in reloads_before:
            lines.extend([
                f"    /* Reload {reload.tensor_name} from slow memory */",
                "    memcpy(",
                f"        _nnc_fast_pool + {reload.to_fast_offset},",
                f"        _nnc_slow_pool + {reload.from_slow_offset},",
                f"        {reload.size}",
                "    );",
                "",
            ])

        lines.append(f"    {func_name}_body();")

        for spill in spills_after:
            lines.extend([
                "",
                f"    /* Spill {spill.tensor_name} to slow memory */",
                "    memcpy(",
                f"        _nnc_slow_pool + {spill.to_slow_offset},",
                f"        _nnc_fast_pool + {spill.from_fast_offset},",
                f"        {spill.size}",
                "    );",
            ])

        lines.append("}")
        lines.append("")

    lines.append("/* Node body functions */")
    emitter = CEmitter(pipeline_schedule_metadata=pipeline_codegen_metadata)
    body_code = emitter.emit(ctx)
    lines.append(backend._process_body_code(body_code, ctx))
    helper_block = backend._render_parallel_step_helper_block(pipeline_codegen_metadata)
    runtime_block = backend._render_parallel_runtime_block(pipeline_codegen_metadata)
    if helper_block:
        lines.append("")
        lines.extend(helper_block)
    if runtime_block:
        lines.append("")
        lines.extend(runtime_block)

    lines.append("")
    lines.append("/* Main inference entry point */")
    lines.append("void nnc_run(void) {")

    if _has_parallel_runtime(pipeline_codegen_metadata):
        lines.append("    nnc_pipeline_run_parallel();")
    else:
        for node in nodes:
            if node.op_type.value == "constant":
                continue
            func_name = ctx.node_symbols.get(node.name, node.name)
            _append_pipeline_step_comment_lines(
                lines,
                pipeline_codegen_metadata,
                node.name,
                backend=backend,
                indent="    ",
            )
            lines.append(f"    {func_name}();")

    lines.append("}")

    return "\n".join(lines)
