/* NNC x86 Runtime - Operator Implementations
 * Reference implementation using standard C
 *
 * Auto-generated by NNC - DO NOT EDIT
 */

#include "nnc_ops.h"
#include "nnc_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Helper: Calculate total number of elements */
static int64_t tensor_numel(Tensor* t) {
    int64_t total = 1;
    for (int i = 0; i < t->ndim; i++) {
        total *= t->shape[i];
    }
    return total;
}

/* ============================================================================
 * Numerical Stability Helpers
 * ============================================================================ */

/* Kahan summation for improved numerical accuracy
 * Reduces floating-point error accumulation from O(n*eps) to O(eps)
 * Returns the accurate sum of n float values starting at data
 */
static float kahan_sum(const float* data, int64_t n) {
    float sum = 0.0f;
    float c = 0.0f;  /* Running compensation for lost low-order bits */

    for (int64_t i = 0; i < n; i++) {
        float y = data[i] - c;   /* Subtract compensation first */
        float t = sum + y;        /* Add to sum */
        c = (t - sum) - y;        /* Update compensation: (sum + y) - sum - y = lost bits */
        sum = t;
    }
    return sum;
}

/* Pairwise summation alternative for better parallelization potential
 * Reduces error by recursively summing pairs (log depth instead of linear)
 */
static float pairwise_sum(const float* data, int64_t n) {
    if (n <= 32) {
        /* Base case: small arrays use direct summation */
        float sum = 0.0f;
        for (int64_t i = 0; i < n; i++) {
            sum += data[i];
        }
        return sum;
    }

    /* Recursive case: split and sum halves */
    int64_t half = n / 2;
    return pairwise_sum(data, half) + pairwise_sum(data + half, n - half);
}

/* ============================================================================
 * Arithmetic Operations
 * ============================================================================ */

void nnc_add(Tensor* a, Tensor* b, Tensor* out) {
    int64_t n = tensor_numel(out);
    int64_t a_n = tensor_numel(a);
    int64_t b_n = tensor_numel(b);
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    /* Handle broadcasting - use minimum size to avoid overflow */
    int64_t copy_n = n;
    if (a_n < copy_n) copy_n = a_n;
    if (b_n < copy_n) copy_n = b_n;

    for (int64_t i = 0; i < copy_n; i++) {
        out_data[i] = a_data[i] + b_data[i];
    }

    /* Handle broadcast: if one input is smaller, broadcast its value */
    if (a_n == 1 && b_n == n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[0] + b_data[i];
        }
    } else if (a_n == n && b_n == 1) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i] + b_data[0];
        }
    } else if (a_n < n && b_n == n) {
        /* Broadcast a (e.g., [6] to [2, 6]) */
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i % a_n] + b_data[i];
        }
    } else if (a_n == n && b_n < n) {
        /* Broadcast b (e.g., [6] to [2, 6]) */
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i] + b_data[i % b_n];
        }
    }
}

void nnc_mul(Tensor* a, Tensor* b, Tensor* out) {
    int64_t n = tensor_numel(out);
    int64_t a_n = tensor_numel(a);
    int64_t b_n = tensor_numel(b);
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    /* Handle broadcasting */
    int64_t copy_n = (a_n < n) ? a_n : n;
    copy_n = (b_n < copy_n) ? b_n : copy_n;

    for (int64_t i = 0; i < copy_n; i++) {
        out_data[i] = a_data[i] * b_data[i];
    }

    if (a_n == 1 && b_n == n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[0] * b_data[i];
        }
    } else if (a_n == n && b_n == 1) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i] * b_data[0];
        }
    } else if (a_n < n && b_n == n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i % a_n] * b_data[i];
        }
    } else if (a_n == n && b_n < n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i] * b_data[i % b_n];
        }
    }
}

void nnc_sub(Tensor* a, Tensor* b, Tensor* out) {
    int64_t n = tensor_numel(out);
    int64_t a_n = tensor_numel(a);
    int64_t b_n = tensor_numel(b);
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    /* Handle broadcasting */
    int64_t copy_n = (a_n < n) ? a_n : n;
    copy_n = (b_n < copy_n) ? b_n : copy_n;

    for (int64_t i = 0; i < copy_n; i++) {
        out_data[i] = a_data[i] - b_data[i];
    }

    if (a_n == 1 && b_n == n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[0] - b_data[i];
        }
    } else if (a_n == n && b_n == 1) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i] - b_data[0];
        }
    } else if (a_n < n && b_n == n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i % a_n] - b_data[i];
        }
    } else if (a_n == n && b_n < n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i] - b_data[i % b_n];
        }
    }
}

void nnc_div(Tensor* a, Tensor* b, Tensor* out) {
    int64_t n = tensor_numel(out);
    int64_t a_n = tensor_numel(a);
    int64_t b_n = tensor_numel(b);
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    /* Handle broadcasting */
    int64_t copy_n = (a_n < n) ? a_n : n;
    copy_n = (b_n < copy_n) ? b_n : copy_n;

    for (int64_t i = 0; i < copy_n; i++) {
        out_data[i] = a_data[i] / b_data[i];
    }

    if (a_n == 1 && b_n == n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[0] / b_data[i];
        }
    } else if (a_n == n && b_n == 1) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i] / b_data[0];
        }
    } else if (a_n < n && b_n == n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i % a_n] / b_data[i];
        }
    } else if (a_n == n && b_n < n) {
        for (int64_t i = copy_n; i < n; i++) {
            out_data[i] = a_data[i] / b_data[i % b_n];
        }
    }
}

/* ============================================================================
 * Activation Functions
 * ============================================================================ */

void nnc_relu(Tensor* input, Tensor* output) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = fmaxf(0.0f, in_data[i]);
    }
}

void nnc_sigmoid(Tensor* input, Tensor* output) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = 1.0f / (1.0f + expf(-in_data[i]));
    }
}

void nnc_tanh(Tensor* input, Tensor* output) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = tanhf(in_data[i]);
    }
}

void nnc_softmax(Tensor* input, Tensor* output, int axis) {
    /* Softmax activation along specified axis */
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    int ndim = input->ndim;

    /* Handle negative axis */
    if (axis < 0) {
        axis = ndim + axis;
    }

    /* Calculate dimensions */
    int64_t outer_size = 1;
    for (int i = 0; i < axis; i++) {
        outer_size *= input->shape[i];
    }

    int64_t softmax_dim = input->shape[axis];
    int64_t inner_size = 1;
    for (int i = axis + 1; i < ndim; i++) {
        inner_size *= input->shape[i];
    }

    /* Perform softmax */
    for (int64_t outer = 0; outer < outer_size; outer++) {
        for (int64_t inner = 0; inner < inner_size; inner++) {
            /* Find max for numerical stability */
            float max_val = -INFINITY;
            for (int64_t s = 0; s < softmax_dim; s++) {
                int64_t idx = outer * softmax_dim * inner_size + s * inner_size + inner;
                if (in_data[idx] > max_val) {
                    max_val = in_data[idx];
                }
            }

            /* Compute sum of exp(x - max) */
            float sum_exp = 0.0f;
            for (int64_t s = 0; s < softmax_dim; s++) {
                int64_t idx = outer * softmax_dim * inner_size + s * inner_size + inner;
                sum_exp += expf(in_data[idx] - max_val);
            }

            /* Compute softmax probabilities */
            for (int64_t s = 0; s < softmax_dim; s++) {
                int64_t idx = outer * softmax_dim * inner_size + s * inner_size + inner;
                out_data[idx] = expf(in_data[idx] - max_val) / sum_exp;
            }
        }
    }
}

/* ============================================================================
 * Pooling Operations (Placeholder implementations)
 * ============================================================================ */

void nnc_maxpool2d(
    Tensor* input, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
) {
    /* 2D Max Pooling implementation
     * Input: [N, C, H, W]
     * Output: [N, C, H_out, W_out]
     * H_out = (H + 2*pad_h - kernel_h) / stride_h + 1
     * W_out = (W + 2*pad_w - kernel_w) / stride_w + 1
     */

    if (!input || !output || !input->data || !output->data) {
        return;
    }
    if (input->ndim != 4 || output->ndim != 4) {
        return;
    }

    int N = (int)input->shape[0];
    int C = (int)input->shape[1];
    int H_in = (int)input->shape[2];
    int W_in = (int)input->shape[3];
    int H_out = (int)output->shape[2];
    int W_out = (int)output->shape[3];

    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    /* Initialize output to minimum float value */
    for (int64_t i = 0; i < tensor_numel(output); i++) {
        out_data[i] = -3.402823e38f;  /* FLT_MIN-ish but for max pool */
    }

    /* Compute max pooling */
    for (int n = 0; n < N; n++) {
        for (int c = 0; c < C; c++) {
            for (int h_out = 0; h_out < H_out; h_out++) {
                for (int w_out = 0; w_out < W_out; w_out++) {
                    /* Calculate input window start position */
                    int h_start = h_out * stride_h - pad_h;
                    int w_start = w_out * stride_w - pad_w;

                    /* Calculate window end position */
                    int h_end = h_start + kernel_h;
                    int w_end = w_start + kernel_w;

                    /* Clamp to input bounds */
                    if (h_start < 0) h_start = 0;
                    if (w_start < 0) w_start = 0;
                    if (h_end > H_in) h_end = H_in;
                    if (w_end > W_in) w_end = W_in;

                    /* Find maximum in window */
                    float max_val = -3.402823e38f;
                    int has_valid = 0;

                    for (int h = h_start; h < h_end; h++) {
                        for (int w = w_start; w < w_end; w++) {
                            int64_t in_idx = ((n * C + c) * H_in + h) * W_in + w;
                            float val = in_data[in_idx];
                            if (!has_valid || val > max_val) {
                                max_val = val;
                                has_valid = 1;
                            }
                        }
                    }

                    /* Write output */
                    int64_t out_idx = ((n * C + c) * H_out + h_out) * W_out + w_out;
                    out_data[out_idx] = max_val;
                }
            }
        }
    }
}

void nnc_avgpool2d(
    Tensor* input, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
) {
    /* 2D Average Pooling implementation
     * Input: [N, C, H, W]
     * Output: [N, C, H_out, W_out]
     * H_out = (H + 2*pad_h - kernel_h) / stride_h + 1
     * W_out = (W + 2*pad_w - kernel_w) / stride_w + 1
     */

    if (!input || !output || !input->data || !output->data) {
        return;
    }
    if (input->ndim != 4 || output->ndim != 4) {
        return;
    }

    int N = (int)input->shape[0];
    int C = (int)input->shape[1];
    int H_in = (int)input->shape[2];
    int W_in = (int)input->shape[3];
    int H_out = (int)output->shape[2];
    int W_out = (int)output->shape[3];

    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    /* Compute average pooling */
    for (int n = 0; n < N; n++) {
        for (int c = 0; c < C; c++) {
            for (int h_out = 0; h_out < H_out; h_out++) {
                for (int w_out = 0; w_out < W_out; w_out++) {
                    /* Calculate input window start position */
                    int h_start = h_out * stride_h - pad_h;
                    int w_start = w_out * stride_w - pad_w;

                    /* Calculate window end position */
                    int h_end = h_start + kernel_h;
                    int w_end = w_start + kernel_w;

                    /* Clamp to input bounds */
                    if (h_start < 0) h_start = 0;
                    if (w_start < 0) w_start = 0;
                    if (h_end > H_in) h_end = H_in;
                    if (w_end > W_in) w_end = W_in;

                    /* Calculate sum and count for averaging */
                    float sum = 0.0f;
                    int count = 0;

                    for (int h = h_start; h < h_end; h++) {
                        for (int w = w_start; w < w_end; w++) {
                            int64_t in_idx = ((n * C + c) * H_in + h) * W_in + w;
                            sum += in_data[in_idx];
                            count++;
                        }
                    }

                    /* Write output (average) */
                    int64_t out_idx = ((n * C + c) * H_out + h_out) * W_out + w_out;
                    out_data[out_idx] = (count > 0) ? (sum / count) : 0.0f;
                }
            }
        }
    }
}

/* ============================================================================
 * Convolution (Placeholder implementation)
 * ============================================================================ */

void nnc_conv(
    Tensor* input, Tensor* weight, Tensor* bias, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
) {
    /* Standard 2D convolution implementation
     * Input: [N, C_in, H, W]
     * Weight: [C_out, C_in, kH, kW]
     * Bias: [C_out] (optional)
     * Output: [N, C_out, H_out, W_out]
     */

    /* Debug: Check pointers */
    fprintf(stderr, "nnc_conv: Checking pointers...\\n");
    fflush(stderr);

    if (!input || !weight || !output) {
        fprintf(stderr, "nnc_conv: NULL tensor pointer\\n");
        fflush(stderr);
        return;
    }
    if (!input->data || !weight->data || !output->data) {
        fprintf(stderr, "nnc_conv: NULL data pointer\\n");
        fprintf(stderr, "  input->data=%p, weight->data=%p, output->data=%p\\n",
                input->data, weight->data, output->data);
        fflush(stderr);
        return;
    }
    if (!input->shape || !weight->shape || !output->shape) {
        fprintf(stderr, "nnc_conv: NULL shape pointer\\n");
        fflush(stderr);
        return;
    }

    fprintf(stderr, "nnc_conv: All pointers valid\\n");
    fflush(stderr);

    /* Extract dimensions */
    int N = (int)input->shape[0];
    int C_in = (int)input->shape[1];
    int H_in = (int)input->shape[2];
    int W_in = (int)input->shape[3];

    int C_out = (int)weight->shape[0];
    int H_out = (int)output->shape[2];
    int W_out = (int)output->shape[3];

    fprintf(stderr, "nnc_conv: dimensions\\n");
    fprintf(stderr, "  input: [%d, %d, %d, %d]\\n", N, C_in, H_in, W_in);
    fprintf(stderr, "  weight: [%d, %d, %d, %d]\\n", C_out, (int)weight->shape[1], (int)weight->shape[2], (int)weight->shape[3]);
    fprintf(stderr, "  output: [%d, %d, %d, %d]\\n", (int)output->shape[0], (int)output->shape[1], H_out, W_out);
    fprintf(stderr, "  kernel: [%d, %d], stride: [%d, %d], pad: [%d, %d]\\n",
            kernel_h, kernel_w, stride_h, stride_w, pad_h, pad_w);
    fflush(stderr);

    /* Get data pointers */
    float* in_data = (float*)input->data;
    float* weight_data = (float*)weight->data;
    float* bias_data = bias ? (float*)bias->data : NULL;
    float* out_data = (float*)output->data;

    /* Compute output dimensions */
    /* H_out = (H_in + 2*pad_h - kernel_h) / stride_h + 1 */
    /* W_out = (W_in + 2*pad_w - kernel_w) / stride_w + 1 */

    /* Initialize output to zero */
    int64_t output_size = N * C_out * H_out * W_out;
    for (int64_t i = 0; i < output_size; i++) {
        out_data[i] = 0.0f;
    }

    /* Perform convolution */
    for (int n = 0; n < N; n++) {
        for (int c_out = 0; c_out < C_out; c_out++) {
            for (int h_out = 0; h_out < H_out; h_out++) {
                for (int w_out = 0; w_out < W_out; w_out++) {
                    /* Compute convolution window start position */
                    int h_in = h_out * stride_h - pad_h;
                    int w_in = w_out * stride_w - pad_w;

                    float sum = 0.0f;

                    /* Convolve over kernel */
                    for (int c_in = 0; c_in < C_in; c_in++) {
                        for (int kh = 0; kh < kernel_h; kh++) {
                            for (int kw = 0; kw < kernel_w; kw++) {
                                int h = h_in + kh;
                                int w = w_in + kw;

                                /* Check bounds */
                                if (h >= 0 && h < H_in && w >= 0 && w < W_in) {
                                    /* Calculate indices */
                                    int64_t in_idx = n * C_in * H_in * W_in
                                                   + c_in * H_in * W_in
                                                   + h * W_in
                                                   + w;

                                    int64_t weight_idx = c_out * C_in * kernel_h * kernel_w
                                                      + c_in * kernel_h * kernel_w
                                                      + kh * kernel_w
                                                      + kw;

                                    sum += in_data[in_idx] * weight_data[weight_idx];
                                }
                            }
                        }
                    }

                    /* Add bias if present */
                    if (bias_data) {
                        sum += bias_data[c_out];
                    }

                    /* Write output */
                    int64_t out_idx = n * C_out * H_out * W_out
                                    + c_out * H_out * W_out
                                    + h_out * W_out
                                    + w_out;
                    out_data[out_idx] = sum;
                }
            }
        }
    }
}

/* ============================================================================
 * Shape Manipulation Operations
 * ============================================================================ */

void nnc_reshape(Tensor* input, Tensor* output, int64_t* shape, int ndim) {
    /* Reshape doesn't change the data, just the shape */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

void nnc_flatten(Tensor* input, Tensor* output, int axis) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

void nnc_transpose(Tensor* input, Tensor* output, int64_t* perm, int ndim) {
    /* Transpose operation with permutation
     * If perm is NULL, reverse the dimensions
     */

    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    int64_t total_elements = tensor_numel(output);

    /* Build permutation array if NULL (reverse permutation) */
    int64_t local_perm[8];  /* Support up to 8 dimensions */
    if (perm == NULL) {
        for (int i = 0; i < ndim; i++) {
            local_perm[i] = ndim - 1 - i;
        }
        perm = local_perm;
    }

    /* Calculate strides for input and output */
    int64_t in_strides[8];
    int64_t out_strides[8];

    in_strides[ndim - 1] = 1;
    for (int i = ndim - 2; i >= 0; i--) {
        in_strides[i] = in_strides[i + 1] * input->shape[i + 1];
    }

    out_strides[ndim - 1] = 1;
    for (int i = ndim - 2; i >= 0; i--) {
        out_strides[i] = out_strides[i + 1] * output->shape[i + 1];
    }

    /* Perform transpose */
    for (int64_t out_idx = 0; out_idx < total_elements; out_idx++) {
        /* Convert output linear index to multi-dimensional indices */
        int64_t temp = out_idx;
        int64_t in_idx = 0;

        for (int i = 0; i < ndim; i++) {
            int64_t out_dim_idx = temp / out_strides[i];
            temp = temp % out_strides[i];

            /* Map output dimension to input dimension using permutation */
            int64_t in_dim = perm[i];
            in_idx += out_dim_idx * in_strides[in_dim];
        }

        out_data[out_idx] = in_data[in_idx];
    }
}

void nnc_squeeze(Tensor* input, Tensor* output, int axis) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

void nnc_unsqueeze(Tensor* input, Tensor* output, int axis) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

/* ============================================================================
 * Matrix Operations
 * ============================================================================ */

void nnc_matmul(Tensor* a, Tensor* b, Tensor* output) {
    /* Matrix multiplication supporting various tensor shapes
     * Handles: 2D matrices, and batched matrix multiplication
     */

    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)output->data;

    int a_ndim = a->ndim;
    int b_ndim = b->ndim;
    int out_ndim = output->ndim;

    if (a_ndim == 2 && b_ndim == 2) {
        /* Standard 2D matrix multiplication: [M, K] @ [K, N] = [M, N] */
        int M = a->shape[0];
        int K = a->shape[1];
        int N = b->shape[1];

        for (int i = 0; i < M; i++) {
            for (int j = 0; j < N; j++) {
                float sum = 0.0f;
                for (int k = 0; k < K; k++) {
                    sum += a_data[i * K + k] * b_data[k * N + j];
                }
                out_data[i * N + j] = sum;
            }
        }
    } else if (a_ndim == 1 && b_ndim == 2) {
        /* Vector @ Matrix: [K] @ [K, N] = [N] */
        int K = a->shape[0];
        int N = b->shape[1];

        for (int j = 0; j < N; j++) {
            float sum = 0.0f;
            for (int k = 0; k < K; k++) {
                sum += a_data[k] * b_data[k * N + j];
            }
            out_data[j] = sum;
        }
    } else if (a_ndim == 2 && b_ndim == 1) {
        /* Matrix @ Vector: [M, K] @ [K] = [M] */
        int M = a->shape[0];
        int K = a->shape[1];

        for (int i = 0; i < M; i++) {
            float sum = 0.0f;
            for (int k = 0; k < K; k++) {
                sum += a_data[i * K + k] * b_data[k];
            }
            out_data[i] = sum;
        }
    } else if (a_ndim >= 2 && b_ndim >= 2) {
        /* Batched matrix multiplication
         * Broadcasting: [B, M, K] @ [B, K, N] or [B, M, K] @ [K, N], etc.
         * When B has fewer dimensions than A, it is broadcast across batches.
         */

        /* Get batch dimensions */
        int64_t batch_size = 1;
        for (int i = 0; i < out_ndim - 2; i++) {
            batch_size *= output->shape[i];
        }

        /* Get matrix dimensions for the last 2 dimensions */
        int M = output->shape[out_ndim - 2];
        int N = output->shape[out_ndim - 1];
        int K = a->shape[a_ndim - 1];

        /* Calculate strides */
        int64_t a_batch_stride = 1;
        for (int i = 0; i < a_ndim; i++) {
            a_batch_stride *= a->shape[i];
        }
        a_batch_stride /= (a->shape[a_ndim - 2] * a->shape[a_ndim - 1]);

        /* For B: if it has fewer batch dimensions than output, it's broadcast (stride = 0) */
        int64_t b_batch_stride = 1;
        if (b_ndim < out_ndim) {
            /* B is 2D while A/output is 3D or higher - broadcast across batches */
            b_batch_stride = 0;
        } else {
            /* B has same number of batch dimensions as output */
            for (int i = 0; i < b_ndim; i++) {
                b_batch_stride *= b->shape[i];
            }
            b_batch_stride /= (b->shape[b_ndim - 2] * b->shape[b_ndim - 1]);
        }

        int64_t out_batch_stride = M * N;

        for (int64_t batch = 0; batch < batch_size; batch++) {
            float* a_batch = a_data + batch * a_batch_stride;
            float* b_batch = b_data + batch * b_batch_stride;
            float* out_batch = out_data + batch * out_batch_stride;

            for (int i = 0; i < M; i++) {
                for (int j = 0; j < N; j++) {
                    float sum = 0.0f;
                    for (int k = 0; k < K; k++) {
                        sum += a_batch[i * K + k] * b_batch[k * N + j];
                    }
                    out_batch[i * N + j] = sum;
                }
            }
        }
    }
}

void nnc_gemm(
    Tensor* a, Tensor* b, Tensor* c, Tensor* output,
    float alpha, float beta, int trans_a, int trans_b
) {
    /* General Matrix Multiply: output = alpha * (A @ B) + beta * C
     *
     * A: input tensor [M, K] or [K, M] if trans_a
     * B: weight tensor [K, N] or [N, K] if trans_b
     * C: bias tensor [N] or [M, N], can be NULL
     * output: [M, N]
     */

    /* Get data pointers */
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* c_data = c ? (float*)c->data : NULL;
    float* out_data = (float*)output->data;

    /* Determine dimensions
     * For 2D tensors:
     * - A: [M, K] (or [K, M] if trans_a)
     * - B: [K, N] (or [N, K] if trans_b)
     * - C: [M, N] (broadcast if 1D)
     * - output: [M, N]
     */
    int M, K, N;

    if (a->ndim == 2 && b->ndim == 2) {
        /* Standard 2D case */
        if (trans_a) {
            K = a->shape[0];
            M = a->shape[1];
        } else {
            M = a->shape[0];
            K = a->shape[1];
        }

        if (trans_b) {
            N = b->shape[0];
            /* K should match: K == b->shape[1] */
        } else {
            N = b->shape[1];
            /* K should match: K == b->shape[0] */
        }
    } else if (a->ndim == 1 && b->ndim == 2) {
        /* Vector x Matrix: [K] x [K, N] -> [N] */
        M = 1;
        K = a->shape[0];
        N = b->shape[1];
        trans_a = 0;  /* Already a vector, no transpose needed */
    } else if (a->ndim == 2 && b->ndim == 1) {
        /* Matrix x Vector: [M, K] x [K] -> [M] */
        M = a->shape[0];
        K = a->shape[1];
        N = 1;
        trans_b = 0;  /* Already a vector, no transpose needed */
    } else {
        /* Fallback: flatten and compute as 2D */
        int64_t a_size = tensor_numel(a);
        int64_t b_size = tensor_numel(b);
        M = 1;
        K = a_size;
        N = b_size;
    }

    /* Compute matrix multiplication
     * output[i][j] = alpha * sum(A[i][k] * B[k][j]) + beta * C[i][j]
     */
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            float sum = 0.0f;

            /* Compute dot product: A[i,:] @ B[:,j] */
            for (int k = 0; k < K; k++) {
                float a_val, b_val;

                /* Get A[i][k] */
                if (trans_a) {
                    a_val = a_data[k * M + i];  /* [K][M] */
                } else {
                    a_val = a_data[i * K + k];  /* [M][K] */
                }

                /* Get B[k][j] */
                if (trans_b) {
                    b_val = b_data[j * K + k];  /* [N][K] */
                } else {
                    b_val = b_data[k * N + j];  /* [K][N] */
                }

                sum += a_val * b_val;
            }

            /* Apply alpha scaling */
            sum *= alpha;

            /* Add bias (if present) with beta scaling */
            if (c_data != NULL) {
                float c_val;
                if (c->ndim == 1) {
                    /* 1D bias: broadcast along output dimension */
                    c_val = c_data[j];
                } else {
                    /* 2D bias: [M, N] */
                    c_val = c_data[i * N + j];
                }
                sum += beta * c_val;
            }

            out_data[i * N + j] = sum;
        }
    }
}

/* ============================================================================
 * Reduction Operations
 * ============================================================================ */

void nnc_reducemean(Tensor* input, Tensor* output, int axis, int keepdims) {
    /* Mean reduction along specified axis */
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    int ndim = input->ndim;

    /* Handle negative axis */
    if (axis < 0) {
        axis = ndim + axis;
    }

    /* Calculate dimensions */
    int64_t outer_size = 1;
    for (int i = 0; i < axis; i++) {
        outer_size *= input->shape[i];
    }

    int64_t reduce_dim = input->shape[axis];
    int64_t inner_size = 1;
    for (int i = axis + 1; i < ndim; i++) {
        inner_size *= input->shape[i];
    }

    /* Perform reduction */
    for (int64_t outer = 0; outer < outer_size; outer++) {
        for (int64_t inner = 0; inner < inner_size; inner++) {
            float sum = 0.0f;
            for (int64_t r = 0; r < reduce_dim; r++) {
                int64_t idx = outer * reduce_dim * inner_size + r * inner_size + inner;
                sum += in_data[idx];
            }
            float mean = sum / (float)reduce_dim;

            /* Calculate output index */
            int64_t out_idx;
            if (keepdims) {
                out_idx = outer * 1 * inner_size + 0 * inner_size + inner;
            } else {
                out_idx = outer * inner_size + inner;
            }
            out_data[out_idx] = mean;
        }
    }
}

void nnc_reducesum(Tensor* input, Tensor* output, int axis, int keepdims) {
    /* Sum reduction along specified axis */
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    int ndim = input->ndim;

    /* Handle negative axis */
    if (axis < 0) {
        axis = ndim + axis;
    }

    /* Calculate dimensions */
    int64_t outer_size = 1;
    for (int i = 0; i < axis; i++) {
        outer_size *= input->shape[i];
    }

    int64_t reduce_dim = input->shape[axis];
    int64_t inner_size = 1;
    for (int i = axis + 1; i < ndim; i++) {
        inner_size *= input->shape[i];
    }

    /* Perform reduction */
    for (int64_t outer = 0; outer < outer_size; outer++) {
        for (int64_t inner = 0; inner < inner_size; inner++) {
            float sum = 0.0f;
            for (int64_t r = 0; r < reduce_dim; r++) {
                int64_t idx = outer * reduce_dim * inner_size + r * inner_size + inner;
                sum += in_data[idx];
            }

            /* Calculate output index */
            int64_t out_idx;
            if (keepdims) {
                out_idx = outer * 1 * inner_size + 0 * inner_size + inner;
            } else {
                out_idx = outer * inner_size + inner;
            }
            out_data[out_idx] = sum;
        }
    }
}

/* ============================================================================
 * Other Operations
 * ============================================================================ */

void nnc_concat(Tensor** inputs, Tensor* output, int num_inputs, int axis) {
    /* Concatenation along specified axis
     * Combines multiple tensors along a given dimension
     * Handles both float32 and int64 data types
     */

    /* Handle negative axis */
    if (axis < 0) {
        axis = output->ndim + axis;
    }

    /* Check if output is INT64 dtype */
    int is_int64 = (output->dtype == 6);  /* NNC_DTYPE_INT64 */

    /* Calculate dimensions before and after concat axis */
    int64_t outer_size = 1;
    for (int i = 0; i < axis; i++) {
        outer_size *= output->shape[i];
    }

    int64_t inner_size = 1;
    for (int i = axis + 1; i < output->ndim; i++) {
        inner_size *= output->shape[i];
    }

    /* Copy data from each input tensor */
    int64_t output_offset = 0;
    for (int input_idx = 0; input_idx < num_inputs; input_idx++) {
        Tensor* input = inputs[input_idx];

        int64_t concat_dim = input->shape[axis];
        int64_t copy_size = concat_dim * inner_size;

        if (is_int64) {
            /* INT64 data path */
            int64_t* out_data = (int64_t*)output->data;
            int64_t* in_data = (int64_t*)input->data;

            for (int64_t outer = 0; outer < outer_size; outer++) {
                int64_t dest_base = outer * output->shape[axis] * inner_size + output_offset;
                int64_t src_base = outer * concat_dim * inner_size;

                for (int64_t i = 0; i < copy_size; i++) {
                    out_data[dest_base + i] = in_data[src_base + i];
                }
            }
        } else {
            /* FLOAT32 data path (default) */
            float* out_data = (float*)output->data;
            float* in_data = (float*)input->data;

            for (int64_t outer = 0; outer < outer_size; outer++) {
                int64_t dest_base = outer * output->shape[axis] * inner_size + output_offset;
                int64_t src_base = outer * concat_dim * inner_size;

                for (int64_t i = 0; i < copy_size; i++) {
                    out_data[dest_base + i] = in_data[src_base + i];
                }
            }
        }

        output_offset += concat_dim * inner_size;
    }
}

void nnc_batchnorm(
    Tensor* input, Tensor* scale, Tensor* bias, Tensor* mean, Tensor* var,
    Tensor* output, float epsilon, int momentum
) {
    /* TODO: Implement actual batch normalization */
}

void nnc_layernorm(
    Tensor* input, Tensor* scale, Tensor* bias, Tensor* output,
    int axis, float epsilon
) {
    /* Layer Normalization implementation
     * Normalizes over the specified axis (typically the last dimension)
     * output = scale * (input - mean) / sqrt(var + epsilon) + bias
     */

    float* in_data = (float*)input->data;
    float* scale_data = scale ? (float*)scale->data : NULL;
    float* bias_data = bias ? (float*)bias->data : NULL;
    float* out_data = (float*)output->data;

    int ndim = input->ndim;

    /* Handle negative axis */
    if (axis < 0) {
        axis = ndim + axis;
    }

    /* Calculate the size of the normalized dimension (feature size) */
    int64_t norm_size = input->shape[axis];

    /* Calculate outer dimensions (number of vectors to normalize) */
    int64_t outer_size = 1;
    for (int i = 0; i < axis; i++) {
        outer_size *= input->shape[i];
    }

    /* Calculate stride between elements in the normalized dimension */
    int64_t inner_size = 1;
    for (int i = axis + 1; i < ndim; i++) {
        inner_size *= input->shape[i];
    }

    /* Process each vector to normalize */
    for (int64_t outer = 0; outer < outer_size; outer++) {
        int64_t base_idx = outer * norm_size * inner_size;

        /* Calculate mean */
        float mean = 0.0f;
        for (int64_t i = 0; i < norm_size; i++) {
            int64_t idx = base_idx + i * inner_size;
            for (int64_t j = 0; j < inner_size; j++) {
                mean += in_data[idx + j];
            }
        }
        mean /= (float)(norm_size * inner_size);

        /* Calculate variance */
        float var = 0.0f;
        for (int64_t i = 0; i < norm_size; i++) {
            int64_t idx = base_idx + i * inner_size;
            for (int64_t j = 0; j < inner_size; j++) {
                float diff = in_data[idx + j] - mean;
                var += diff * diff;
            }
        }
        var /= (float)(norm_size * inner_size);

        /* Calculate standard deviation */
        float std = sqrtf(var + epsilon);

        /* Apply normalization: y = scale * (x - mean) / std + bias */
        for (int64_t i = 0; i < norm_size; i++) {
            int64_t idx = base_idx + i * inner_size;
            float scale_val = scale_data ? scale_data[i] : 1.0f;
            float bias_val = bias_data ? bias_data[i] : 0.0f;

            for (int64_t j = 0; j < inner_size; j++) {
                float normalized = (in_data[idx + j] - mean) / std;
                out_data[idx + j] = scale_val * normalized + bias_val;
            }
        }
    }
}

void nnc_identity(Tensor* input, Tensor* output) {
    /* Identity operation - copy input to output */
    int64_t n = tensor_numel(output);
    int64_t input_n = tensor_numel(input);
    int64_t copy_n = (n < input_n) ? n : input_n;

    /* Use memcpy for safe copy (handles overlap and aliasing correctly) */
    memcpy(output->data, input->data, copy_n * sizeof(float));
}

void nnc_split(Tensor* input, Tensor** outputs, int num_outputs, int axis) {
    /* Split operation - divide tensor along axis
     * For simplicity, this implementation assumes equal splits
     * A full implementation would handle variable split sizes
     */

    float* in_data = (float*)input->data;

    /* Handle negative axis */
    if (axis < 0) {
        axis = input->ndim + axis;
    }

    /* Calculate dimensions before and after split axis */
    int64_t outer_size = 1;
    for (int i = 0; i < axis; i++) {
        outer_size *= input->shape[i];
    }

    int64_t split_dim = input->shape[axis];
    int64_t split_size = split_dim / num_outputs;

    int64_t inner_size = 1;
    for (int i = axis + 1; i < input->ndim; i++) {
        inner_size *= input->shape[i];
    }

    /* Copy data to each output */
    for (int out_idx = 0; out_idx < num_outputs; out_idx++) {
        Tensor* out = outputs[out_idx];
        float* out_data = (float*)out->data;

        for (int outer = 0; outer < outer_size; outer++) {
            /* Calculate source offset for this output */
            int64_t base_src = outer * split_dim * inner_size + out_idx * split_size * inner_size;

            /* Copy this slice */
            int64_t copy_size = split_size * inner_size;
            int64_t dest_offset = outer * split_size * inner_size;

            for (int64_t i = 0; i < copy_size; i++) {
                out_data[dest_offset + i] = in_data[base_src + i];
            }
        }
    }
}

void nnc_clip(Tensor* input, Tensor* output, float min_val, float max_val) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        float val = in_data[i];
        out_data[i] = fminf(fmaxf(val, min_val), max_val);
    }
}

void nnc_tile(Tensor* input, Tensor* output, int64_t* repeats, int ndim) {
    /* Tile operation - repeats input tensor along each axis
     * repeats[i] specifies how many times to repeat axis i
     * If repeats is NULL, treat as all 1s (no repetition)
     */

    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    /* If no repeats specified, just copy */
    if (repeats == NULL) {
        int64_t n = tensor_numel(output);
        for (int64_t i = 0; i < n; i++) {
            out_data[i] = in_data[i];
        }
        return;
    }

    /* Calculate strides for input and output tensors */
    int64_t in_strides[8];  /* Max 8 dimensions */
    int64_t out_strides[8];

    /* Compute input strides (row-major) */
    in_strides[input->ndim - 1] = 1;
    for (int i = input->ndim - 2; i >= 0; i--) {
        in_strides[i] = in_strides[i + 1] * input->shape[i + 1];
    }

    /* Compute output strides (row-major) */
    out_strides[output->ndim - 1] = 1;
    for (int i = output->ndim - 2; i >= 0; i--) {
        out_strides[i] = out_strides[i + 1] * output->shape[i + 1];
    }

    /* Broadcast repeats to match input rank if needed */
    int64_t tiled_repeats[8];
    int repeats_offset = ndim > input->ndim ? ndim - input->ndim : 0;

    for (int i = 0; i < input->ndim; i++) {
        int repeats_idx = i + repeats_offset;
        if (repeats_idx < ndim && repeats_idx >= 0) {
            tiled_repeats[i] = repeats[repeats_idx];
        } else {
            tiled_repeats[i] = 1;
        }
    }

    /* Copy data with tiling */
    int64_t out_idx = 0;
    int64_t total_out = tensor_numel(output);

    /* Iterate through output positions */
    for (int64_t out_pos = 0; out_pos < total_out; out_pos++) {
        /* Calculate corresponding input position */
        int64_t in_pos = 0;

        /* Decompose output position to coordinates */
        int64_t temp = out_pos;
        int64_t out_coords[8];
        for (int i = output->ndim - 1; i >= 0; i--) {
            out_coords[i] = temp % output->shape[i];
            temp /= output->shape[i];
        }

        /* Map output coordinates to input coordinates */
        for (int i = 0; i < input->ndim; i++) {
            int64_t coord = out_coords[i] % input->shape[i];
            in_pos += coord * in_strides[i];
        }

        out_data[out_pos] = in_data[in_pos];
    }
}

/* ============================================================================
 * Comparison Operations
 * ============================================================================ */

void nnc_equal(Tensor* a, Tensor* b, Tensor* out) {
    /* Element-wise equality comparison
     * Returns 1.0f where a == b, 0.0f otherwise
     */
    int64_t n = tensor_numel(out);
    int64_t a_n = tensor_numel(a);
    int64_t b_n = tensor_numel(b);

    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    /* Handle broadcasting - use minimum size */
    int64_t compare_n = n;
    if (a_n < compare_n) compare_n = a_n;
    if (b_n < compare_n) compare_n = b_n;

    /* Compare elements */
    for (int64_t i = 0; i < compare_n; i++) {
        out_data[i] = (a_data[i] == b_data[i]) ? 1.0f : 0.0f;
    }

    /* Handle broadcast: if one input is smaller, broadcast its value */
    if (a_n == 1 && b_n == n) {
        for (int64_t i = compare_n; i < n; i++) {
            out_data[i] = (a_data[0] == b_data[i]) ? 1.0f : 0.0f;
        }
    } else if (a_n == n && b_n == 1) {
        for (int64_t i = compare_n; i < n; i++) {
            out_data[i] = (a_data[i] == b_data[0]) ? 1.0f : 0.0f;
        }
    } else if (a_n < n && b_n == n) {
        /* Broadcast a (e.g., [6] to [2, 6]) */
        for (int64_t i = compare_n; i < n; i++) {
            out_data[i] = (a_data[i % a_n] == b_data[i]) ? 1.0f : 0.0f;
        }
    } else if (a_n == n && b_n < n) {
        /* Broadcast b (e.g., [6] to [2, 6]) */
        for (int64_t i = compare_n; i < n; i++) {
            out_data[i] = (a_data[i] == b_data[i % b_n]) ? 1.0f : 0.0f;
        }
    }
}

void nnc_and(Tensor* a, Tensor* b, Tensor* out) {
    /* Logical AND operation
     * Inputs are float (non-zero = true), output is float (1.0 = true, 0.0 = false)
     */
    int64_t n = tensor_numel(out);
    int64_t a_n = tensor_numel(a);
    int64_t b_n = tensor_numel(b);

    const float* a_data = (float*)a->data;
    const float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    /* Handle broadcasting */
    int64_t and_n = n;
    if (a_n < and_n) and_n = a_n;
    if (b_n < and_n) and_n = b_n;

    /* Compute AND for overlapping region */
    for (int64_t i = 0; i < and_n; i++) {
        out_data[i] = (a_data[i] != 0.0f && b_data[i] != 0.0f) ? 1.0f : 0.0f;
    }

    /* Handle broadcast: if one input is smaller, broadcast its value */
    if (a_n == 1 && b_n == n) {
        for (int64_t i = and_n; i < n; i++) {
            out_data[i] = (a_data[0] != 0.0f && b_data[i] != 0.0f) ? 1.0f : 0.0f;
        }
    } else if (a_n == n && b_n == 1) {
        for (int64_t i = and_n; i < n; i++) {
            out_data[i] = (a_data[i] != 0.0f && b_data[0] != 0.0f) ? 1.0f : 0.0f;
        }
    } else if (a_n < n && b_n == n) {
        /* Broadcast a (e.g., [2] to [2, 2]) */
        for (int64_t i = and_n; i < n; i++) {
            out_data[i] = (a_data[i % a_n] != 0.0f && b_data[i] != 0.0f) ? 1.0f : 0.0f;
        }
    } else if (a_n == n && b_n < n) {
        /* Broadcast b (e.g., [2] to [2, 2]) */
        for (int64_t i = and_n; i < n; i++) {
            out_data[i] = (a_data[i] != 0.0f && b_data[i % b_n] != 0.0f) ? 1.0f : 0.0f;
        }
    }
}

/* ============================================================================
 * Math Operations (Unary Element-wise)
 * ============================================================================ */

void nnc_sqrt(Tensor* input, Tensor* output) {
    /* Element-wise square root operation
     * Computes sqrt(x) for each element
     */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        float x = in_data[i];
        /* Handle negative inputs - return NaN for sqrt of negative numbers */
        out_data[i] = (x >= 0.0f) ? sqrtf(x) : NAN;
    }
}

void nnc_pow(Tensor* input, Tensor* output) {
    /* Element-wise power operation (x^2)
     * Used for LayerNorm variance computation
     * Computes x^2 for each element
     */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i] * in_data[i];
    }
}

void nnc_exp(Tensor* input, Tensor* output) {
    /* Element-wise exponential operation
     * Computes exp(x) for each element
     */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = expf(in_data[i]);
    }
}

void nnc_log(Tensor* input, Tensor* output) {
    /* Element-wise natural logarithm operation
     * Computes log(x) for each element
     */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        float x = in_data[i];
        /* Handle non-positive inputs - return NaN */
        out_data[i] = (x > 0.0f) ? logf(x) : NAN;
    }
}

void nnc_abs(Tensor* input, Tensor* output) {
    /* Element-wise absolute value operation
     * Computes |x| for each element
     */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = fabsf(in_data[i]);
    }
}

void nnc_neg(Tensor* input, Tensor* output) {
    /* Element-wise negation operation
     * Computes -x for each element
     */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = -in_data[i];
    }
}

void nnc_cast(Tensor* input, Tensor* output, int to_dtype) {
    /* Cast operation - convert tensor data type
     * to_dtype: NNC_DTYPE_* constant
     */
    int64_t n = tensor_numel(input);

    /* Check if input is BOOL type by checking dtype field */
    int is_bool_input = (input->dtype == NNC_DTYPE_BOOL);

    switch (to_dtype) {
        case NNC_DTYPE_FLOAT32: {
            if (is_bool_input) {
                /* BOOL to FLOAT32 - convert properly */
                const uint8_t* in_data = (uint8_t*)input->data;
                float* out_data = (float*)output->data;
                for (int64_t i = 0; i < n; i++) {
                    out_data[i] = (float)in_data[i];
                }
            } else {
                /* Float to float - copy */
                memcpy(output->data, input->data, n * sizeof(float));
            }
            break;
        }
        case NNC_DTYPE_FLOAT16:
            /* Float to float - copy (with size conversion) */
            memcpy(output->data, input->data, n * sizeof(float));
            break;
        case NNC_DTYPE_INT32: {
            int32_t* out_data = (int32_t*)output->data;
            if (is_bool_input) {
                /* BOOL to INT32 - convert properly */
                const uint8_t* in_data = (uint8_t*)input->data;
                for (int64_t i = 0; i < n; i++) {
                    out_data[i] = (int32_t)in_data[i];
                }
            } else {
                /* Float to int32 */
                const float* in_data = (float*)input->data;
                for (int64_t i = 0; i < n; i++) {
                    out_data[i] = (int32_t)in_data[i];
                }
            }
            break;
        }
        case NNC_DTYPE_INT64: {
            int64_t* out_data = (int64_t*)output->data;
            if (is_bool_input) {
                /* BOOL to INT64 - convert properly */
                const uint8_t* in_data = (uint8_t*)input->data;
                for (int64_t i = 0; i < n; i++) {
                    out_data[i] = (int64_t)in_data[i];
                }
            } else {
                /* Float to int64 */
                const float* in_data = (float*)input->data;
                for (int64_t i = 0; i < n; i++) {
                    out_data[i] = (int64_t)in_data[i];
                }
            }
            break;
        }
        case NNC_DTYPE_BOOL: {
            uint8_t* out_data = (uint8_t*)output->data;
            if (is_bool_input) {
                /* BOOL to BOOL - just copy */
                const uint8_t* in_data = (uint8_t*)input->data;
                memcpy(out_data, in_data, n);
            } else {
                /* Float to bool (non-zero is true) */
                const float* in_data = (float*)input->data;
                for (int64_t i = 0; i < n; i++) {
                    out_data[i] = in_data[i] != 0.0f ? 1 : 0;
                }
            }
            break;
        }
        default:
            /* Unsupported cast, copy as fallback */
            memcpy(output->data, input->data, n * sizeof(float));
            break;
    }
}

void nnc_shape(Tensor* input, Tensor* output, int64_t* shape_data, int ndim) {
    /* Shape operation - extracts the shape of input tensor
     * If shape_data is provided, use it (compile-time known shape)
     * Otherwise, extract from input tensor
     */
    int64_t* out_data = (int64_t*)output->data;

    if (shape_data != NULL) {
        /* Compile-time known shape - just copy */
        for (int i = 0; i < ndim; i++) {
            out_data[i] = shape_data[i];
        }
    } else {
        /* Runtime shape extraction */
        for (int i = 0; i < ndim; i++) {
            out_data[i] = input->shape[i];
        }
    }
}

void nnc_constantofshape(Tensor* output, float value, int ndim) {
    /* ConstantOfShape operation - create tensor filled with value
     * The shape is determined from the tensor's shape field
     */
    int64_t n = tensor_numel(output);
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = value;
    }
}

void nnc_expand(Tensor* input, Tensor* output, int64_t* shape, int ndim) {
    /* Expand operation - broadcast tensor to larger shape
     * For simplicity, we just copy the data with broadcasting logic
     * In a full implementation, this would handle proper broadcasting
     */
    int64_t in_n = tensor_numel(input);
    int64_t out_n = tensor_numel(output);

    const float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    if (in_n == out_n) {
        /* Same size, just copy */
        memcpy(out_data, in_data, in_n * sizeof(float));
    } else {
        /* Simple broadcast - repeat input data */
        for (int64_t i = 0; i < out_n; i++) {
            out_data[i] = in_data[i % in_n];
        }
    }
}

void nnc_greater(Tensor* a, Tensor* b, Tensor* out) {
    /* Greater comparison: out = (a > b)
     * Output is uint8_t (BOOL type)
     * Supports broadcasting when one input is scalar (1 element)
     */
    int64_t n = tensor_numel(out);
    int64_t a_n = tensor_numel(a);
    int64_t b_n = tensor_numel(b);
    const float* a_data = (float*)a->data;
    const float* b_data = (float*)b->data;
    uint8_t* out_data = (uint8_t*)out->data;

    for (int64_t i = 0; i < n; i++) {
        float a_val = a_data[i % a_n];
        float b_val = b_data[i % b_n];
        out_data[i] = a_val > b_val ? 1 : 0;
    }
}

void nnc_or(Tensor* a, Tensor* b, Tensor* out) {
    /* Logical OR operation
     * Inputs and output are uint8_t (BOOL type)
     */
    int64_t n = tensor_numel(out);
    const uint8_t* a_data = (uint8_t*)a->data;
    const uint8_t* b_data = (uint8_t*)b->data;
    uint8_t* out_data = (uint8_t*)out->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = a_data[i] || b_data[i] ? 1 : 0;
    }
}

void nnc_not(Tensor* input, Tensor* output) {
    /* Logical NOT operation
     * Input and output are uint8_t (BOOL type)
     */
    int64_t n = tensor_numel(output);
    const uint8_t* in_data = (uint8_t*)input->data;
    uint8_t* out_data = (uint8_t*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = !in_data[i] ? 1 : 0;
    }
}

/* ============================================================================
 * Indexing Operations
 * ============================================================================ */

void nnc_gather(Tensor* data, Tensor* indices, Tensor* output, int axis, int data_dtype) {
    /* Gather operation: extract elements from data along specified axis
     * output[i][j][...] = data[i][indices[j]][...] for axis=1, etc.
     *
     * data_dtype: 0 for float, 1 for int64 (for shape tensors)
     */
    const int64_t* indices_data = (int64_t*)indices->data;

    /* Get tensor shapes */
    int64_t data_rank = data->ndim;
    int64_t indices_rank = indices->ndim;
    int64_t output_rank = output->ndim;

    /* Handle negative axis */
    if (axis < 0) {
        axis = data_rank + axis;
    }

    /* Clamp axis to valid range */
    if (axis < 0) axis = 0;
    if (axis >= data_rank) axis = data_rank - 1;

    /* Calculate total elements in output */
    int64_t output_n = tensor_numel(output);

    /* Simple case: scalar indices (0D) or single-element 1D */
    if (indices_rank == 0 || (indices_rank == 1 && indices->shape[0] == 1)) {
        int64_t gather_index = indices_data[0];

        /* Handle negative indices */
        int64_t dim_size = data->shape[axis];
        if (gather_index < 0) {
            gather_index += dim_size;
        }

        /* Clamp to valid range */
        if (gather_index < 0) gather_index = 0;
        if (gather_index >= dim_size) gather_index = dim_size - 1;

        /* Handle INT64 data (e.g., from Shape operator) */
        if (data_dtype == 1) {
            const int64_t* data_data = (int64_t*)data->data;
            int64_t* output_data = (int64_t*)output->data;

            /* For 1D data */
            if (data_rank == 1) {
                output_data[0] = data_data[gather_index];
                return;
            }

            /* For multi-dimensional data with scalar index, gather along axis */
            /* Simply copy remaining dimensions */
            int64_t copy_size = 1;
            for (int i = axis + 1; i < data_rank; i++) {
                copy_size *= data->shape[i];
            }
            for (int i = 0; i < copy_size; i++) {
                output_data[i] = data_data[gather_index * copy_size + i];
            }
            return;
        }

        /* Handle FLOAT data (default) */
        const float* data_data = (float*)data->data;
        float* output_data = (float*)output->data;

        /* For 1D data */
        if (data_rank == 1) {
            for (int64_t i = 0; i < output_n; i++) {
                output_data[i] = data_data[gather_index];
            }
            return;
        }

        /* For 2D data */
        if (data_rank == 2 && output_rank == 2) {
            int64_t dim1_size = data->shape[1];
            int64_t out_dim0 = output->shape[0];
            int64_t out_dim1 = output->shape[1];

            for (int64_t i = 0; i < out_dim0; i++) {
                for (int64_t j = 0; j < out_dim1; j++) {
                    if (axis == 0) {
                        output_data[i * out_dim1 + j] = data_data[gather_index * dim1_size + j];
                    } else {
                        output_data[i * out_dim1 + j] = data_data[i * dim1_size + gather_index];
                    }
                }
            }
            return;
        }

        /* For 3D data (common in LSTM) */
        if (data_rank == 3) {
            int64_t d0 = data->shape[0], d1 = data->shape[1], d2 = data->shape[2];

            /* Output has shape [d1, d2] if axis=0, or [d0, d2] if axis=1, or [d0, d1] if axis=2 */
            if (axis == 0 && output_rank == 2) {
                /* Gather along axis 0: output[i,j] = data[gather_index, j, k]... wait, that's wrong
                 * Actually: output[i,j] = data[gather_index, i, j] for scalar gather
                 */
                for (int64_t i = 0; i < d1; i++) {
                    for (int64_t j = 0; j < d2; j++) {
                        int64_t src_idx = gather_index * d1 * d2 + i * d2 + j;
                        output_data[i * d2 + j] = data_data[src_idx];
                    }
                }
                return;
            } else if (axis == 0 && output_rank == 3) {
                /* For some cases, output might still be 3D */
                int64_t o0 = output->shape[0], o1 = output->shape[1], o2 = output->shape[2];
                for (int64_t i = 0; i < o0; i++) {
                    for (int64_t j = 0; j < o1; j++) {
                        for (int64_t k = 0; k < o2; k++) {
                            int64_t src_idx = gather_index * d1 * d2 + j * d2 + k;
                            output_data[i * o1 * o2 + j * o2 + k] = data_data[src_idx];
                        }
                    }
                }
                return;
            } else if (axis == 1) {
                /* Gather along axis 1 */
                for (int64_t i = 0; i < d0; i++) {
                    for (int64_t k = 0; k < d2; k++) {
                        int64_t src_idx = i * d1 * d2 + gather_index * d2 + k;
                        int64_t out_idx = i * d2 + k;
                        output_data[out_idx] = data_data[src_idx];
                    }
                }
                return;
            } else if (axis == 2) {
                /* Gather along axis 2 */
                for (int64_t i = 0; i < d0; i++) {
                    for (int64_t j = 0; j < d1; j++) {
                        int64_t src_idx = i * d1 * d2 + j * d2 + gather_index;
                        int64_t out_idx = i * d1 + j;
                        output_data[out_idx] = data_data[src_idx];
                    }
                }
                return;
            }
        }
    }

    /* General case: 1D indices tensor */
    if (indices_rank == 1) {
        int64_t num_indices = indices->shape[0];

        /* Handle INT64 data */
        if (data_dtype == 1) {
            const int64_t* data_data = (int64_t*)data->data;
            int64_t* output_data = (int64_t*)output->data;

            if (data_rank == 1) {
                for (int i = 0; i < num_indices; i++) {
                    int64_t idx = indices_data[i];
                    if (idx < 0) idx += data->shape[0];
                    if (idx < 0) idx = 0;
                    if (idx >= data->shape[0]) idx = data->shape[0] - 1;
                    output_data[i] = data_data[idx];
                }
                return;
            }
        }

        /* Handle FLOAT data */
        const float* data_data = (float*)data->data;
        float* output_data = (float*)output->data;

        /* For 2D data with 1D indices */
        if (data_rank == 2) {
            int64_t dim1_size = data->shape[1];
            for (int64_t idx = 0; idx < num_indices; idx++) {
                int64_t gather_index = indices_data[idx];
                if (gather_index < 0) gather_index += data->shape[axis];
                if (gather_index < 0) gather_index = 0;
                if (gather_index >= data->shape[axis]) gather_index = data->shape[axis] - 1;

                if (axis == 0) {
                    for (int64_t j = 0; j < dim1_size; j++) {
                        output_data[idx * dim1_size + j] = data_data[gather_index * dim1_size + j];
                    }
                } else {
                    for (int64_t i = 0; i < data->shape[0]; i++) {
                        output_data[i * num_indices + idx] = data_data[i * dim1_size + gather_index];
                    }
                }
            }
            return;
        }
    }

    /* Fallback: element-by-element copy */
    if (data_dtype == 1) {
        const int64_t* data_data = (int64_t*)data->data;
        int64_t* output_data = (int64_t*)output->data;
        int64_t data_n = tensor_numel(data);
        for (int64_t i = 0; i < output_n; i++) {
            output_data[i] = data_data[i % data_n];
        }
    } else {
        const float* data_data = (float*)data->data;
        float* output_data = (float*)output->data;
        int64_t data_n = tensor_numel(data);
        for (int64_t i = 0; i < output_n; i++) {
            output_data[i] = data_data[i % data_n];
        }
    }
}

/* ============================================================================
 * RNN Operations
 * ============================================================================ */

/* LSTM activation functions */
static float sigmoid_f(float x) {
    return 1.0f / (1.0f + expf(-x));
}

static float tanh_f(float x) {
    return tanhf(x);
}

/* LSTM cell computation for one time step
 * Computes:
 *   i_t = sigmoid(W_i * x_t + R_i * h_{t-1} + b_i)
 *   o_t = sigmoid(W_o * x_t + R_o * h_{t-1} + b_o)
 *   f_t = sigmoid(W_f * x_t + R_f * h_{t-1} + b_f)
 *   g_t = tanh(W_c * x_t + R_c * h_{t-1} + b_c)
 *   c_t = f_t * c_{t-1} + i_t * g_t
 *   h_t = o_t * tanh(c_t)
 *
 * ONNX LSTM weight format: I, O, F, C (Input, Output, Forget, Cell)
 * W: [4*hidden_size, input_size] - row-major: each row is hidden_size elements
 * R: [4*hidden_size, hidden_size] - row-major
 * B: [8*hidden_size] - [W_b_i, W_b_o, W_b_f, W_b_c, R_b_i, R_b_o, R_b_f, R_b_c]
 */
static void lstm_cell(
    const float* x_t,        /* Input at time t: [input_size] */
    const float* h_prev,     /* Previous hidden state: [hidden_size] */
    const float* c_prev,     /* Previous cell state: [hidden_size] */
    const float* W,          /* Input weights: [4*hidden_size, input_size] */
    const float* R,          /* Hidden weights: [4*hidden_size, hidden_size] */
    const float* B,          /* Bias: [8*hidden_size] or NULL */
    float* h_next,           /* Next hidden state: [hidden_size] */
    float* c_next,           /* Next cell state: [hidden_size] */
    int input_size,
    int hidden_size
) {
    /* ONNX LSTM gate order: I, O, F, C (Input, Output, Forget, Cell) */

    /* Compute all gates at once for efficiency */
    for (int i = 0; i < hidden_size; i++) {
        /* Input gate (i_t) - ONNX index: 0, row: i */
        float i_gate = 0.0f;
        const float* W_i = W + 0 * hidden_size * input_size + i * input_size;
        const float* R_i = R + 0 * hidden_size * hidden_size + i * hidden_size;
        for (int j = 0; j < input_size; j++) {
            i_gate += W_i[j] * x_t[j];
        }
        for (int j = 0; j < hidden_size; j++) {
            i_gate += R_i[j] * h_prev[j];
        }
        if (B) {
            i_gate += B[0 * hidden_size + i] + B[4 * hidden_size + i];
        }
        i_gate = sigmoid_f(i_gate);

        /* Output gate (o_t) - ONNX index: 1, row: i */
        float o_gate = 0.0f;
        const float* W_o = W + 1 * hidden_size * input_size + i * input_size;
        const float* R_o = R + 1 * hidden_size * hidden_size + i * hidden_size;
        for (int j = 0; j < input_size; j++) {
            o_gate += W_o[j] * x_t[j];
        }
        for (int j = 0; j < hidden_size; j++) {
            o_gate += R_o[j] * h_prev[j];
        }
        if (B) {
            o_gate += B[1 * hidden_size + i] + B[5 * hidden_size + i];
        }
        o_gate = sigmoid_f(o_gate);

        /* Forget gate (f_t) - ONNX index: 2, row: i */
        float f_gate = 0.0f;
        const float* W_f = W + 2 * hidden_size * input_size + i * input_size;
        const float* R_f = R + 2 * hidden_size * hidden_size + i * hidden_size;
        for (int j = 0; j < input_size; j++) {
            f_gate += W_f[j] * x_t[j];
        }
        for (int j = 0; j < hidden_size; j++) {
            f_gate += R_f[j] * h_prev[j];
        }
        if (B) {
            f_gate += B[2 * hidden_size + i] + B[6 * hidden_size + i];
        }
        f_gate = sigmoid_f(f_gate);

        /* Cell gate (g_t) - ONNX index: 3, row: i */
        float g_gate = 0.0f;
        const float* W_c = W + 3 * hidden_size * input_size + i * input_size;
        const float* R_c = R + 3 * hidden_size * hidden_size + i * hidden_size;
        for (int j = 0; j < input_size; j++) {
            g_gate += W_c[j] * x_t[j];
        }
        for (int j = 0; j < hidden_size; j++) {
            g_gate += R_c[j] * h_prev[j];
        }
        if (B) {
            g_gate += B[3 * hidden_size + i] + B[7 * hidden_size + i];
        }
        g_gate = tanh_f(g_gate);

        /* Update cell state: c_t = f_t * c_{t-1} + i_t * g_t */
        c_next[i] = f_gate * c_prev[i] + i_gate * g_gate;

        /* Update hidden state: h_t = o_t * tanh(c_t) */
        h_next[i] = o_gate * tanh_f(c_next[i]);
    }
}

void nnc_lstm(
    Tensor* X, Tensor* W, Tensor* R, Tensor* B,
    Tensor* Y, Tensor* Y_h, Tensor* Y_c,
    int direction, int hidden_size
) {
    /* LSTM operation
     * Assumes layout=0 (seq_length, batch_size, input_size) for input X
     * Outputs are in ONNX format
     */

    /* Get dimensions */
    int64_t seq_len = X->shape[0];
    int64_t batch_size = X->shape[1];
    int64_t input_size = X->shape[2];

    const float* X_data = (float*)X->data;
    const float* W_data = (float*)W->data;
    const float* R_data = (float*)R->data;
    const float* B_data = B ? (float*)B->data : NULL;

    float* Y_data = (float*)Y->data;
    float* Y_h_data = (float*)Y_h->data;
    float* Y_c_data = (float*)Y_c->data;

    /* For each direction (forward/bidirectional) */
    for (int dir = 0; dir < (direction == 2 ? 2 : 1); dir++) {
        /* Initialize hidden and cell states to zero */
        float* h = (float*)malloc(hidden_size * sizeof(float));
        float* c = (float*)malloc(hidden_size * sizeof(float));
        for (int i = 0; i < hidden_size; i++) {
            h[i] = 0.0f;
            c[i] = 0.0f;
        }

        /* Pointer to weights for this direction */
        const float* W_dir = W_data + dir * 4 * hidden_size * input_size;
        const float* R_dir = R_data + dir * 4 * hidden_size * hidden_size;
        const float* B_dir = NULL;
        if (B_data) {
            B_dir = B_data + dir * 8 * hidden_size;
        }

        /* Process sequence */
        for (int t = 0; t < seq_len; t++) {
            /* Determine time step index (reverse for backward direction) */
            int t_idx = (dir == 1) ? (seq_len - 1 - t) : t;

            /* Process each batch */
            for (int b = 0; b < batch_size; b++) {
                /* Get input for this time step and batch */
                const float* x_t = X_data + t_idx * batch_size * input_size + b * input_size;

                /* Compute LSTM cell */
                float* h_new = (float*)malloc(hidden_size * sizeof(float));
                float* c_new = (float*)malloc(hidden_size * sizeof(float));

                lstm_cell(x_t, h, c, W_dir, R_dir, B_dir, h_new, c_new, input_size, hidden_size);

                /* Update states */
                for (int i = 0; i < hidden_size; i++) {
                    h[i] = h_new[i];
                    c[i] = c_new[i];
                }
                free(h_new);
                free(c_new);

                /* Write output */
                /* ONNX output format: Y[seq_len][num_directions][batch_size][hidden_size] */
                int64_t y_idx = t * (direction == 2 ? 2 : 1) * batch_size * hidden_size +
                                 dir * batch_size * hidden_size +
                                 b * hidden_size;
                for (int i = 0; i < hidden_size; i++) {
                    Y_data[y_idx + i] = h[i];
                }
            }
        }

        /* Write final hidden and cell states */
        /* Y_h and Y_c format: [num_directions][batch_size][hidden_size] */
        for (int b = 0; b < batch_size; b++) {
            int64_t h_idx = dir * batch_size * hidden_size + b * hidden_size;
            for (int i = 0; i < hidden_size; i++) {
                Y_h_data[h_idx + i] = h[i];
                Y_c_data[h_idx + i] = c[i];
            }
        }

        free(h);
        free(c);
    }
}
