/* NNC x86 Runtime - Operator Implementations
 * Reference implementation using standard C
 *
 * Auto-generated by NNC - DO NOT EDIT
 */

#include "nnc_ops.h"
#include "nnc_runtime.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>

/* Helper: Calculate total number of elements */
static int64_t tensor_numel(Tensor* t) {
    int64_t total = 1;
    for (int i = 0; i < t->ndim; i++) {
        total *= t->shape[i];
    }
    return total;
}

/* ============================================================================
 * Arithmetic Operations
 * ============================================================================ */

void nnc_add(Tensor* a, Tensor* b, Tensor* out) {
    int64_t n = tensor_numel(out);
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = a_data[i] + b_data[i];
    }
}

void nnc_mul(Tensor* a, Tensor* b, Tensor* out) {
    int64_t n = tensor_numel(out);
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = a_data[i] * b_data[i];
    }
}

void nnc_sub(Tensor* a, Tensor* b, Tensor* out) {
    int64_t n = tensor_numel(out);
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = a_data[i] - b_data[i];
    }
}

void nnc_div(Tensor* a, Tensor* b, Tensor* out) {
    int64_t n = tensor_numel(out);
    float* a_data = (float*)a->data;
    float* b_data = (float*)b->data;
    float* out_data = (float*)out->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = a_data[i] / b_data[i];
    }
}

/* ============================================================================
 * Activation Functions
 * ============================================================================ */

void nnc_relu(Tensor* input, Tensor* output) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = fmaxf(0.0f, in_data[i]);
    }
}

void nnc_sigmoid(Tensor* input, Tensor* output) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = 1.0f / (1.0f + expf(-in_data[i]));
    }
}

void nnc_tanh(Tensor* input, Tensor* output) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = tanhf(in_data[i]);
    }
}

void nnc_softmax(Tensor* input, Tensor* output, int axis) {
    /* Simplified implementation - assumes axis is the last dimension */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    /* For simplicity, just copy input to output */
    /* A proper implementation would compute softmax along the specified axis */
    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

/* ============================================================================
 * Pooling Operations (Placeholder implementations)
 * ============================================================================ */

void nnc_maxpool2d(
    Tensor* input, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
) {
    /* TODO: Implement actual 2D max pooling */
    /* For now, just copy input to output */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    int64_t copy_n = (n < tensor_numel(input)) ? n : tensor_numel(input);
    for (int64_t i = 0; i < copy_n; i++) {
        out_data[i] = in_data[i];
    }
}

void nnc_avgpool2d(
    Tensor* input, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
) {
    /* TODO: Implement actual 2D average pooling */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    int64_t copy_n = (n < tensor_numel(input)) ? n : tensor_numel(input);
    for (int64_t i = 0; i < copy_n; i++) {
        out_data[i] = in_data[i];
    }
}

/* ============================================================================
 * Convolution (Placeholder implementation)
 * ============================================================================ */

void nnc_conv(
    Tensor* input, Tensor* weight, Tensor* bias, Tensor* output,
    int kernel_h, int kernel_w,
    int stride_h, int stride_w,
    int pad_h, int pad_w
) {
    /* Standard 2D convolution implementation
     * Input: [N, C_in, H, W]
     * Weight: [C_out, C_in, kH, kW]
     * Bias: [C_out] (optional)
     * Output: [N, C_out, H_out, W_out]
     */

    /* Debug: Check pointers */
    fprintf(stderr, "nnc_conv: Checking pointers...\\n");
    fflush(stderr);

    if (!input || !weight || !output) {
        fprintf(stderr, "nnc_conv: NULL tensor pointer\\n");
        fflush(stderr);
        return;
    }
    if (!input->data || !weight->data || !output->data) {
        fprintf(stderr, "nnc_conv: NULL data pointer\\n");
        fprintf(stderr, "  input->data=%p, weight->data=%p, output->data=%p\\n",
                input->data, weight->data, output->data);
        fflush(stderr);
        return;
    }
    if (!input->shape || !weight->shape || !output->shape) {
        fprintf(stderr, "nnc_conv: NULL shape pointer\\n");
        fflush(stderr);
        return;
    }

    fprintf(stderr, "nnc_conv: All pointers valid\\n");
    fflush(stderr);

    /* Extract dimensions */
    int N = input->shape[0];
    int C_in = input->shape[1];
    int H_in = input->shape[2];
    int W_in = input->shape[3];

    int C_out = weight->shape[0];
    int H_out = output->shape[2];
    int W_out = output->shape[3];

    fprintf(stderr, "nnc_conv: dimensions\\n");
    fprintf(stderr, "  input: [%d, %d, %d, %d]\\n", N, C_in, H_in, W_in);
    fprintf(stderr, "  weight: [%d, %d, %d, %d]\\n", C_out, weight->shape[1], weight->shape[2], weight->shape[3]);
    fprintf(stderr, "  output: [%d, %d, %d, %d]\\n", (int)output->shape[0], (int)output->shape[1], H_out, W_out);
    fprintf(stderr, "  kernel: [%d, %d], stride: [%d, %d], pad: [%d, %d]\\n",
            kernel_h, kernel_w, stride_h, stride_w, pad_h, pad_w);
    fflush(stderr);

    /* Get data pointers */
    float* in_data = (float*)input->data;
    float* weight_data = (float*)weight->data;
    float* bias_data = bias ? (float*)bias->data : NULL;
    float* out_data = (float*)output->data;

    /* Compute output dimensions */
    /* H_out = (H_in + 2*pad_h - kernel_h) / stride_h + 1 */
    /* W_out = (W_in + 2*pad_w - kernel_w) / stride_w + 1 */

    /* Initialize output to zero */
    int64_t output_size = N * C_out * H_out * W_out;
    for (int64_t i = 0; i < output_size; i++) {
        out_data[i] = 0.0f;
    }

    /* Perform convolution */
    for (int n = 0; n < N; n++) {
        for (int c_out = 0; c_out < C_out; c_out++) {
            for (int h_out = 0; h_out < H_out; h_out++) {
                for (int w_out = 0; w_out < W_out; w_out++) {
                    /* Compute convolution window start position */
                    int h_in = h_out * stride_h - pad_h;
                    int w_in = w_out * stride_w - pad_w;

                    float sum = 0.0f;

                    /* Convolve over kernel */
                    for (int c_in = 0; c_in < C_in; c_in++) {
                        for (int kh = 0; kh < kernel_h; kh++) {
                            for (int kw = 0; kw < kernel_w; kw++) {
                                int h = h_in + kh;
                                int w = w_in + kw;

                                /* Check bounds */
                                if (h >= 0 && h < H_in && w >= 0 && w < W_in) {
                                    /* Calculate indices */
                                    int64_t in_idx = n * C_in * H_in * W_in
                                                   + c_in * H_in * W_in
                                                   + h * W_in
                                                   + w;

                                    int64_t weight_idx = c_out * C_in * kernel_h * kernel_w
                                                      + c_in * kernel_h * kernel_w
                                                      + kh * kernel_w
                                                      + kw;

                                    sum += in_data[in_idx] * weight_data[weight_idx];
                                }
                            }
                        }
                    }

                    /* Add bias if present */
                    if (bias_data) {
                        sum += bias_data[c_out];
                    }

                    /* Write output */
                    int64_t out_idx = n * C_out * H_out * W_out
                                    + c_out * H_out * W_out
                                    + h_out * W_out
                                    + w_out;
                    out_data[out_idx] = sum;
                }
            }
        }
    }
}

/* ============================================================================
 * Shape Manipulation Operations
 * ============================================================================ */

void nnc_reshape(Tensor* input, Tensor* output, int64_t* shape, int ndim) {
    /* Reshape doesn't change the data, just the shape */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

void nnc_flatten(Tensor* input, Tensor* output, int axis) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

void nnc_transpose(Tensor* input, Tensor* output, int64_t* perm, int ndim) {
    /* TODO: Implement actual transpose */
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

void nnc_squeeze(Tensor* input, Tensor* output, int axis) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

void nnc_unsqueeze(Tensor* input, Tensor* output, int axis) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = in_data[i];
    }
}

/* ============================================================================
 * Matrix Operations
 * ============================================================================ */

void nnc_matmul(Tensor* a, Tensor* b, Tensor* output) {
    /* TODO: Implement actual matrix multiplication */
    int64_t n = tensor_numel(output);
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = 0.0f;
    }
}

void nnc_gemm(
    Tensor* a, Tensor* b, Tensor* c, Tensor* output,
    float alpha, float beta, int trans_a, int trans_b
) {
    /* TODO: Implement actual GEMM */
    int64_t n = tensor_numel(output);
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        out_data[i] = 0.0f;
    }
}

/* ============================================================================
 * Reduction Operations
 * ============================================================================ */

void nnc_reducemean(Tensor* input, Tensor* output, int axis, int keepdims) {
    /* TODO: Implement actual mean reduction */
}

void nnc_reducesum(Tensor* input, Tensor* output, int axis, int keepdims) {
    /* TODO: Implement actual sum reduction */
}

/* ============================================================================
 * Other Operations
 * ============================================================================ */

void nnc_concat(Tensor** inputs, Tensor* output, int num_inputs, int axis) {
    /* TODO: Implement actual concatenation */
}

void nnc_batchnorm(
    Tensor* input, Tensor* scale, Tensor* bias, Tensor* mean, Tensor* var,
    Tensor* output, float epsilon, int momentum
) {
    /* TODO: Implement actual batch normalization */
}

void nnc_layernorm(
    Tensor* input, Tensor* scale, Tensor* bias, Tensor* output,
    int axis, float epsilon
) {
    /* Layer Normalization implementation
     * Normalizes over the specified axis (typically the last dimension)
     * output = scale * (input - mean) / sqrt(var + epsilon) + bias
     */

    float* in_data = (float*)input->data;
    float* scale_data = scale ? (float*)scale->data : NULL;
    float* bias_data = bias ? (float*)bias->data : NULL;
    float* out_data = (float*)output->data;

    int ndim = input->ndim;

    /* Handle negative axis */
    if (axis < 0) {
        axis = ndim + axis;
    }

    /* Calculate the size of the normalized dimension (feature size) */
    int64_t norm_size = input->shape[axis];

    /* Calculate outer dimensions (number of vectors to normalize) */
    int64_t outer_size = 1;
    for (int i = 0; i < axis; i++) {
        outer_size *= input->shape[i];
    }

    /* Calculate stride between elements in the normalized dimension */
    int64_t inner_size = 1;
    for (int i = axis + 1; i < ndim; i++) {
        inner_size *= input->shape[i];
    }

    /* Process each vector to normalize */
    for (int64_t outer = 0; outer < outer_size; outer++) {
        int64_t base_idx = outer * norm_size * inner_size;

        /* Calculate mean */
        float mean = 0.0f;
        for (int64_t i = 0; i < norm_size; i++) {
            int64_t idx = base_idx + i * inner_size;
            for (int64_t j = 0; j < inner_size; j++) {
                mean += in_data[idx + j];
            }
        }
        mean /= (float)(norm_size * inner_size);

        /* Calculate variance */
        float var = 0.0f;
        for (int64_t i = 0; i < norm_size; i++) {
            int64_t idx = base_idx + i * inner_size;
            for (int64_t j = 0; j < inner_size; j++) {
                float diff = in_data[idx + j] - mean;
                var += diff * diff;
            }
        }
        var /= (float)(norm_size * inner_size);

        /* Calculate standard deviation */
        float std = sqrtf(var + epsilon);

        /* Apply normalization: y = scale * (x - mean) / std + bias */
        for (int64_t i = 0; i < norm_size; i++) {
            int64_t idx = base_idx + i * inner_size;
            float scale_val = scale_data ? scale_data[i] : 1.0f;
            float bias_val = bias_data ? bias_data[i] : 0.0f;

            for (int64_t j = 0; j < inner_size; j++) {
                float normalized = (in_data[idx + j] - mean) / std;
                out_data[idx + j] = scale_val * normalized + bias_val;
            }
        }
    }
}

void nnc_clip(Tensor* input, Tensor* output, float min_val, float max_val) {
    int64_t n = tensor_numel(output);
    float* in_data = (float*)input->data;
    float* out_data = (float*)output->data;

    for (int64_t i = 0; i < n; i++) {
        float val = in_data[i];
        out_data[i] = fminf(fmaxf(val, min_val), max_val);
    }
}
