# Temporary file for the new test runner generator

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from nnc_py.ir.context import CompileContext


def _generate_test_runner(ctx: "CompileContext") -> str:
    """Generate test runner."""
    # Generate tensor setup code
    tensor_setups = []

    # Setup input tensors
    for tensor_name in ctx.graph.inputs:
        tensor = ctx.graph.get_tensor(tensor_name)
        var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
        size = tensor.byte_size()

        # Generate shape array
        shape_list = tensor.shape.dims
        shape_init = ", ".join(str(d) for d in shape_list)

        # Setup code
        tensor_setups.append(f"    /* Setup {var_name} */")
        tensor_setups.append(f"    static int64_t {var_name}_shape[] = {{{shape_init}}};")
        tensor_setups.append(f"    {var_name}.shape = {var_name}_shape;")
        tensor_setups.append(f"    {var_name}.ndim = {len(shape_list)};")
        tensor_setups.append(f"    {var_name}.dtype = NNC_DTYPE_FLOAT32;")
        tensor_setups.append(f"    {var_name}.nbytes = {size};")
        tensor_setups.append(f"    {var_name}.data = malloc({size});")
        tensor_setups.append(f"    if (!{var_name}.data) {{ fprintf(stderr, \"Failed to allocate {var_name}\\\\n\"); return 1; }}")

        # Initialize with test pattern
        num_elements = size // 4
        tensor_setups.append(f"    for (int i = 0; i < {num_elements}; i++) {{")
        tensor_setups.append(f"        ((float*){var_name}.data)[i] = (float)i * 0.01f;  /* Test pattern */")
        tensor_setups.append(f"    }}")
        tensor_setups.append("")

    # Setup intermediate and output tensors
    for tensor_name, tensor in ctx.graph.tensors.items():
        if tensor_name in ctx.graph.inputs or tensor_name in ctx.graph.constants:
            continue

        var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
        size = tensor.byte_size()
        shape_list = tensor.shape.dims
        shape_init = ", ".join(str(d) for d in shape_list)

        tensor_setups.append(f"    /* Setup {var_name} */")
        tensor_setups.append(f"    static int64_t {var_name}_shape[] = {{{shape_init}}};")
        tensor_setups.append(f"    {var_name}.shape = {var_name}_shape;")
        tensor_setups.append(f"    {var_name}.ndim = {len(shape_list)};")
        tensor_setups.append(f"    {var_name}.dtype = NNC_DTYPE_FLOAT32;")
        tensor_setups.append(f"    {var_name}.nbytes = {size};")
        tensor_setups.append(f"    {var_name}.data = calloc({size // 4}, sizeof(float));  /* Initialize to zero */")
        tensor_setups.append(f"    if (!{var_name}.data) {{ fprintf(stderr, \"Failed to allocate {var_name}\\\\n\"); return 1; }}")
        tensor_setups.append("")

    # Free memory
    tensor_frees = []
    for tensor_name in ctx.graph.tensors:
        if tensor_name in ctx.graph.constants:
            continue
        var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
        tensor_frees.append(f"    free({var_name}.data);")

    setup_code = "\n".join(tensor_setups)
    frees_code = "\n".join(tensor_frees)

    return f"""/* Auto-generated by NNC - DO NOT EDIT */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "nnc_types.h"
#include "model.h"

int main(void) {{
    printf("NNC Model Runner\\n");
    printf("================\\n");

    /* Setup all tensors */
{setup_code}

    /* Print input info */
    printf("Input data (first 10):\\n");
    int64_t input_size = 1;
    for (int i = 0; i < input.ndim; i++) {{
        input_size *= input.shape[i];
    }}
    for (int i = 0; i < 10 && i < input_size; i++) {{
        printf("  input[%d] = %f\\n", i, ((float*)input.data)[i]);
    }}

    /* Run inference */
    printf("\\nRunning inference...\\n");
    nnc_run();

    /* Print output results */
    printf("\\nOutput results (first 10):\\n");
    int64_t output_size = 1;
    for (int i = 0; i < output.ndim; i++) {{
        output_size *= output.shape[i];
    }}
    for (int i = 0; i < 10 && i < output_size; i++) {{
        printf("  output[%d] = %f\\n", i, ((float*)output.data)[i]);
    }}

    /* Free memory */
{frees_code}

    printf("\\nInference complete.\\n");
    return 0;
}}
"""
