"""C code emitter for generating C11 code."""

from io import StringIO

from nnc_py.ir.context import CompileContext
from nnc_py.ir.node import Node
from nnc_py.ir.types import DataType


class CEmitter:
    """C code emitter - generates C11 standard code."""

    def __init__(self):
        self.indent = 0
        self.output = StringIO()

    def emit(self, ctx: CompileContext) -> str:
        """Emit complete C code."""
        self._emit_includes(ctx)
        self._emit_declarations(ctx)
        self._emit_functions(ctx)
        self._emit_entry_point(ctx)
        return self.output.getvalue()

    def _emit_includes(self, ctx: CompileContext):
        """Emit include statements."""
        self.write_line("/* Auto-generated by NNC - DO NOT EDIT */")
        self.write_line()
        self.write_line("#include <stdio.h>")
        self.write_line("#include <stdlib.h>")
        self.write_line('#include "nnc_runtime.h"')
        self.write_line('#include "nnc_ops.h"')
        self.write_line()

    def _emit_declarations(self, ctx: CompileContext):
        """Emit variable declarations."""
        self.write_line("/* Tensor declarations */")
        for tensor_name, tensor in ctx.graph.tensors.items():
            if tensor_name in ctx.graph.constants:
                continue  # Constants are defined in constants.c

            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            self.write_line(f"extern Tensor {var_name};")

        # Declare constant tensors (defined in constants.c)
        for tensor_name in ctx.graph.constants:
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            self.write_line(f"extern Tensor {var_name};")

        self.write_line()

    def _emit_functions(self, ctx: CompileContext):
        """Emit computation functions."""
        nodes = ctx.graph.topological_sort()

        # Generate function for each node
        for node in nodes:
            self._emit_node_function(ctx, node)

    def _emit_node_function(self, ctx: CompileContext, node: Node):
        """Emit function for a single node."""
        func_name = ctx.node_symbols.get(node.name, node.name)

        self.write_line(f"/* {node.op_type.value}: {node.name} */")
        self.write_line(f"void {func_name}(void) {{")
        self.indent += 1

        # Emit operator call
        self._emit_operator_call(ctx, node)

        self.indent -= 1
        self.write_line("}")
        self.write_line()

    def _emit_operator_call(self, ctx: CompileContext, node: Node):
        """Emit operator function call."""
        from nnc_py.ir.node import OpType

        op_name = f"nnc_{node.op_type.value.lower()}"

        # Prepare arguments
        args = []

        # Special handling for Conv operation
        if node.op_type == OpType.CONV2D:
            # Conv requires: input, weight, bias, output
            # bias might be missing (use NULL)
            if len(node.inputs) >= 1:
                var_name = ctx.tensor_symbols.get(node.inputs[0], node.inputs[0])
                args.append(f"&{var_name}")  # input
            if len(node.inputs) >= 2:
                var_name = ctx.tensor_symbols.get(node.inputs[1], node.inputs[1])
                args.append(f"&{var_name}")  # weight

            # bias parameter
            if len(node.inputs) >= 3:
                var_name = ctx.tensor_symbols.get(node.inputs[2], node.inputs[2])
                args.append(f"&{var_name}")  # bias
            else:
                args.append("NULL")  # No bias

            # Output tensor
            if len(node.outputs) >= 1:
                var_name = ctx.tensor_symbols.get(node.outputs[0], node.outputs[0])
                args.append(f"&{var_name}")  # output
        elif node.op_type == OpType.LAYER_NORM:
            # LayerNormalization: input, scale, bias, output
            # scale and bias might be missing (use NULL)
            if len(node.inputs) >= 1:
                var_name = ctx.tensor_symbols.get(node.inputs[0], node.inputs[0])
                args.append(f"&{var_name}")  # input

            # scale (gamma) parameter
            if len(node.inputs) >= 2:
                var_name = ctx.tensor_symbols.get(node.inputs[1], node.inputs[1])
                args.append(f"&{var_name}")  # scale
            else:
                args.append("NULL")

            # bias (beta) parameter
            if len(node.inputs) >= 3:
                var_name = ctx.tensor_symbols.get(node.inputs[2], node.inputs[2])
                args.append(f"&{var_name}")  # bias
            else:
                args.append("NULL")

            # Output tensor
            if len(node.outputs) >= 1:
                var_name = ctx.tensor_symbols.get(node.outputs[0], node.outputs[0])
                args.append(f"&{var_name}")  # output

            # axis and epsilon parameters
            axis = node.attrs.get("axis", -1)
            epsilon = node.attrs.get("epsilon", 1e-5)
            args.append(f"{axis}")
            args.append(f"{epsilon}f")
        else:
            # Generic handling for other operations
            # Input tensors
            for input_name in node.inputs:
                var_name = ctx.tensor_symbols.get(input_name, input_name)
                args.append(f"&{var_name}")

            # Output tensors
            for output_name in node.outputs:
                var_name = ctx.tensor_symbols.get(output_name, output_name)
                args.append(f"&{var_name}")

        # Add attribute parameters
        attr_args = self._format_attributes(node)
        args.extend(attr_args)

        # Emit function call
        self.write_line(f"{op_name}({', '.join(args)});")

    def _format_attributes(self, node: Node) -> list[str]:
        """Format node attributes as C arguments."""
        args = []

        # Handle common attributes
        if "kernel_shape" in node.attrs:
            kh, kw = node.attrs["kernel_shape"]
            args.append(f"{kh}, {kw}")

        if "strides" in node.attrs:
            sh, sw = node.attrs["strides"]
            args.append(f"{sh}, {sw}")

        if "pads" in node.attrs:
            # ONNX pads: [pad_top, pad_left, pad_bottom, pad_right]
            # Runtime expects: pad_h, pad_w (assuming symmetric padding)
            pads = node.attrs["pads"]
            if len(pads) == 4:
                # Use top and left padding values
                args.append(f"{pads[0]}, {pads[1]}")
            elif len(pads) == 2:
                args.append(f"{pads[0]}, {pads[1]}")

        if "axis" in node.attrs:
            args.append(str(node.attrs["axis"]))

        if "keepdims" in node.attrs:
            args.append(str(node.attrs["keepdims"]))

        return args

    def _emit_entry_point(self, ctx: CompileContext):
        """Emit main entry point function."""
        self.write_line("/* Main inference entry point */")
        self.write_line("void nnc_run(void) {")
        self.indent += 1

        # Call each node function in topological order
        for node in ctx.graph.topological_sort():
            func_name = ctx.node_symbols.get(node.name, node.name)
            self.write_line(f"{func_name}();")

        self.indent -= 1
        self.write_line("}")

    def write_line(self, text: str = ""):
        """Write a line with proper indentation."""
        self.output.write("    " * self.indent + text + "\n")

    def _map_dtype(self, dtype: DataType) -> str:
        """Map IR dtype to C dtype."""
        mapping = {
            DataType.FLOAT32: "float",
            DataType.FLOAT16: "uint16_t",
            DataType.INT32: "int32_t",
            DataType.INT8: "int8_t",
            DataType.UINT8: "uint8_t",
            DataType.BOOL: "uint8_t",
        }
        return mapping.get(dtype, "float")
