"""x86 backend for simulation."""

import numpy as np

from nnc_py.codegen.base import BackendBase, CodeGenResult
from nnc_py.codegen.c_emitter import CEmitter
from nnc_py.ir.context import CompileContext
from nnc_py.ir.types import DataType
from nnc_py.utils.name_manager import NameManager


class X86Backend(BackendBase):
    """x86 target backend - generates code for simulation."""

    def generate(self, ctx: CompileContext) -> CodeGenResult:
        """Generate x86 C code."""
        result = CodeGenResult()

        # Assign C symbol names
        self._assign_symbols(ctx)

        # Generate header file
        header = self._generate_header(ctx)
        result.add_file("model.h", header, "header")

        # Generate source file
        source = self._generate_source(ctx)
        result.add_file("model.c", source, "source")

        # Generate tensors definition file
        tensors = self._generate_tensors(ctx)
        result.add_file("tensors.c", tensors, "source")

        # Generate constants data file
        if ctx.graph.constants:
            constants = self._generate_constants(ctx)
            result.add_file("constants.c", constants, "source")

        # Generate Makefile
        makefile = self._generate_makefile(ctx)
        result.add_file("Makefile", makefile, "build")

        # Generate test runner
        test_runner = self._generate_test_runner(ctx)
        result.add_file("test_runner.c", test_runner, "source")

        return result

    def _generate_source(self, ctx: CompileContext) -> str:
        """Generate main source file."""
        # Need to pass tensor type info to emitter
        from nnc_py.codegen.c_emitter import CEmitter
        emitter = CEmitter()
        return emitter.emit(ctx)

    def _generate_header(self, ctx: CompileContext) -> str:
        """Generate header file."""
        lines = [
            "/* Auto-generated by NTC - DO NOT EDIT */",
            "#ifndef MODEL_H",
            "#define MODEL_H",
            "",
            "#include <stdint.h>",
            '#include "nnc_types.h"',
            "",
            "/* Tensor declarations */",
        ]

        # Declare all non-constant tensors
        for tensor_name in ctx.graph.inputs:
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            lines.append(f"extern Tensor {var_name};")

        for tensor_name, tensor in ctx.graph.tensors.items():
            if tensor_name in ctx.graph.inputs or tensor_name in ctx.graph.constants:
                continue
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            lines.append(f"extern Tensor {var_name};")

        for tensor_name in ctx.graph.outputs:
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            if f"extern Tensor {var_name};" not in lines:
                lines.append(f"extern Tensor {var_name};")

        # Declare constant tensors (defined in constants.c)
        for tensor_name in ctx.graph.constants:
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            if f"extern Tensor {var_name};" not in lines:
                lines.append(f"extern Tensor {var_name};")

        # Declare constant data arrays for use in shape operations
        import numpy as np
        for tensor_name, arr in ctx.graph.constants.items():
            # Only declare INT64 arrays (used for shapes)
            if arr.dtype == np.int64 or arr.dtype == np.int32:
                var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
                dtype = "int64_t" if arr.dtype == np.int64 else "int32_t"
                size = arr.size
                lines.append(f"extern const {dtype} {var_name}_data[{size}];")

        lines.extend([
            "",
            "/* Main inference function */",
            "void nnc_run(void);",
            "",
            "#endif  // MODEL_H",
        ])

        return "\n".join(lines)

    def _generate_constants(self, ctx: CompileContext) -> str:
        """Generate constants data file."""
        lines = [
            "/* Auto-generated by NNC - DO NOT EDIT */",
            '#include "nnc_runtime.h"',
            "",
        ]

        import numpy as np

        for name, arr in ctx.graph.constants.items():
            tensor = ctx.graph.get_tensor(name)
            # Get correct dtype based on array type
            dtype, element_size, nnc_dtype = self._get_constant_type_info(arr)
            size = arr.size
            data = arr.flatten().tolist()
            shape = list(arr.shape)

            # Use sanitized C symbol name
            var_name = ctx.tensor_symbols.get(name, name)

            # For INT64/INT32 constants (used as shapes), make data array non-static
            # so it can be accessed from model.c for reshape operations
            is_shape_constant = (arr.dtype == np.int64 or arr.dtype == np.int32)
            storage_class = "" if is_shape_constant else "static "

            lines.append(f"/* Constant: {name} */")
            lines.append(f"{storage_class}const {dtype} {var_name}_data[{size}] = {{")

            # Format data with multiple values per line
            values_per_line = 10
            for i in range(0, size, values_per_line):
                chunk = data[i:i + values_per_line]
                if dtype == "float":
                    line_values = ", ".join(f"{x:.9g}" for x in chunk)
                else:
                    # Integer types - format as integers
                    line_values = ", ".join(f"{int(x)}" for x in chunk)
                if i + values_per_line < size:
                    line_values += ","
                lines.append(f"    {line_values}")

            lines.append("};")
            lines.append("")

            # Generate Tensor structure
            shape_str = ", ".join(str(s) for s in shape)
            lines.append(f"static const int64_t {var_name}_shape[] = {{{shape_str}}};")
            lines.append(f"Tensor {var_name} = {{")
            lines.append(f"    .data = (void*){var_name}_data,")
            lines.append(f"    .dtype = {nnc_dtype},")
            lines.append(f"    .shape = (int64_t*){var_name}_shape,")
            lines.append(f"    .ndim = {len(shape)},")
            lines.append(f"    .nbytes = {size * element_size},")
            lines.append("};")
            lines.append("")

        return "\n".join(lines)

    def _get_constant_type_info(self, arr: np.ndarray) -> tuple[str, int, str]:
        """Get C type, element size, and NNC dtype enum for a constant array.

        Returns:
            Tuple of (c_dtype, element_size, nnc_dtype_enum)
        """
        import numpy as np

        if arr.dtype == np.float32:
            return "float", 4, "NNC_DTYPE_FLOAT32"
        elif arr.dtype == np.float64:
            return "double", 8, "NNC_DTYPE_FLOAT32"
        elif arr.dtype == np.float16:
            return "uint16_t", 2, "NNC_DTYPE_FLOAT16"
        elif arr.dtype == np.int64:
            return "int64_t", 8, "NNC_DTYPE_INT64"
        elif arr.dtype == np.int32:
            return "int32_t", 4, "NNC_DTYPE_INT32"
        elif arr.dtype == np.int8:
            return "int8_t", 1, "NNC_DTYPE_INT8"
        elif arr.dtype == np.uint8:
            return "uint8_t", 1, "NNC_DTYPE_UINT8"
        elif arr.dtype == np.bool_:
            return "uint8_t", 1, "NNC_DTYPE_BOOL"
        else:
            # Default to float32
            return "float", 4, "NNC_DTYPE_FLOAT32"

    def _generate_makefile(self, ctx: CompileContext) -> str:
        """Generate Makefile."""
        has_constants = bool(ctx.graph.constants)
        objs = "model.o tensors.o"
        if has_constants:
            objs += " constants.o"
        objs += " test_runner.o ops.o"

        # Determine runtime path relative to the output directory
        # For installed package: use NNC_RUNTIME_PATH env var
        # For development: relative path from output to project root
        return f"""# Auto-generated by NNC - DO NOT EDIT
# Set NNC_RUNTIME_PATH to point to the runtime directory if not in dev tree
CC = gcc
CFLAGS = -std=c11 -O2 -Wall -Wextra
LDFLAGS = -lm

# Runtime include path - can be overridden by environment
NNC_RUNTIME ?= ../../runtime
CFLAGS += -I$(NNC_RUNTIME)/include

.PHONY: all clean run

all: model

model: {objs}
\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

ops.o:
\t$(CC) $(CFLAGS) -c $(NNC_RUNTIME)/x86/ops.c

%.o: %.c
\t$(CC) $(CFLAGS) -c $<

clean:
\trm -f *.o model

run: model
\t./model
"""

    def _generate_tensors(self, ctx: CompileContext) -> str:
        """Generate tensors definition file."""
        lines = [
            "/* Auto-generated by NNC - DO NOT EDIT */",
            '#include "nnc_types.h"',
            "",
        ]

        # Define all non-constant tensors
        for tensor_name, tensor in ctx.graph.tensors.items():
            if tensor_name in ctx.graph.constants:
                continue

            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            shape_list = tensor.shape.dims
            shape_init = ", ".join(str(d) for d in shape_list)

            lines.append(f"/* Tensor: {tensor_name} */")
            lines.append(f"int64_t {var_name}_shape[] = {{{shape_init}}};")
            lines.append(f"Tensor {var_name} = {{")
            lines.append(f"    .data = NULL,")
            lines.append(f"    .dtype = NNC_DTYPE_FLOAT32,")
            lines.append(f"    .shape = {var_name}_shape,")
            lines.append(f"    .ndim = {len(shape_list)},")
            lines.append(f"    .nbytes = {tensor.byte_size()},")
            lines.append("};")
            lines.append("")

        return "\n".join(lines)

    def _generate_test_runner(self, ctx: CompileContext) -> str:
        """Generate test runner."""
        # Generate tensor setup code
        tensor_setups = []

        # Setup input tensors
        for tensor_name in ctx.graph.inputs:
            tensor = ctx.graph.get_tensor(tensor_name)
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            size = tensor.byte_size()

            # Generate shape array
            shape_list = tensor.shape.dims
            shape_init = ", ".join(str(d) for d in shape_list)

            # Setup code
            tensor_setups.append(f"    /* Setup {var_name} */")
            tensor_setups.append(f"    static int64_t {var_name}_shape[] = {{{shape_init}}};")
            tensor_setups.append(f"    {var_name}.shape = {var_name}_shape;")
            tensor_setups.append(f"    {var_name}.ndim = {len(shape_list)};")
            tensor_setups.append(f"    {var_name}.dtype = NNC_DTYPE_FLOAT32;")
            tensor_setups.append(f"    {var_name}.nbytes = {size};")
            tensor_setups.append(f"    {var_name}.data = malloc({size});")
            tensor_setups.append(f"    if (!{var_name}.data) {{ fprintf(stderr, \"Failed to allocate {var_name}\\\\n\"); return 1; }}")

            # Initialize with test pattern
            num_elements = size // 4
            tensor_setups.append(f"    for (int i = 0; i < {num_elements}; i++) {{")
            tensor_setups.append(f"        ((float*){var_name}.data)[i] = (float)i * 0.01f;  /* Test pattern */")
            tensor_setups.append(f"    }}")
            tensor_setups.append("")

        # Setup intermediate and output tensors
        for tensor_name, tensor in ctx.graph.tensors.items():
            if tensor_name in ctx.graph.inputs or tensor_name in ctx.graph.constants:
                continue

            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            size = tensor.byte_size()
            shape_list = tensor.shape.dims
            shape_init = ", ".join(str(d) for d in shape_list)

            tensor_setups.append(f"    /* Setup {var_name} */")
            tensor_setups.append(f"    static int64_t {var_name}_shape[] = {{{shape_init}}};")
            tensor_setups.append(f"    {var_name}.shape = {var_name}_shape;")
            tensor_setups.append(f"    {var_name}.ndim = {len(shape_list)};")
            tensor_setups.append(f"    {var_name}.dtype = NNC_DTYPE_FLOAT32;")
            tensor_setups.append(f"    {var_name}.nbytes = {size};")
            tensor_setups.append(f"    {var_name}.data = calloc({size // 4}, sizeof(float));  /* Initialize to zero */")
            tensor_setups.append(f"    if (!{var_name}.data) {{ fprintf(stderr, \"Failed to allocate {var_name}\\\\n\"); return 1; }}")
            tensor_setups.append("")

        # Free memory
        tensor_frees = []
        for tensor_name in ctx.graph.tensors:
            if tensor_name in ctx.graph.constants:
                continue
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            tensor_frees.append(f"    free({var_name}.data);")

        setup_code = "\n".join(tensor_setups)
        frees_code = "\n".join(tensor_frees)

        # Get input and output tensor variable names
        input_var = None
        if ctx.graph.inputs:
            input_name = ctx.graph.inputs[0]
            input_var = ctx.tensor_symbols.get(input_name, input_name)

        output_var = None
        if ctx.graph.outputs:
            output_name = ctx.graph.outputs[0]
            output_var = ctx.tensor_symbols.get(output_name, output_name)

        # Generate print code only if we have input/output tensors
        print_code = ""
        if input_var and output_var:
            print_code = f"""
    /* Print input info */
    printf("Input data (first 10):\\\\n");
    int64_t input_size = 1;
    for (int i = 0; i < {input_var}.ndim; i++) {{
        input_size *= {input_var}.shape[i];
    }}
    for (int i = 0; i < 10 && i < input_size; i++) {{
        printf("  input[%d] = %f\\\\n", i, ((float*){input_var}.data)[i]);
    }}

    /* Run inference */
    printf("\\\\nRunning inference...\\\\n");
    nnc_run();

    /* Print output results */
    printf("\\\\nOutput results (first 10):\\\\n");
    int64_t output_size = 1;
    for (int i = 0; i < {output_var}.ndim; i++) {{
        output_size *= {output_var}.shape[i];
    }}
    for (int i = 0; i < 10 && i < output_size; i++) {{
        printf("  output[%d] = %f\\\\n", i, ((float*){output_var}.data)[i]);
    }}"""
        else:
            print_code = """
    /* Run inference */
    printf("\\nRunning inference...\\n");
    nnc_run();"""

        return f"""/* Auto-generated by NNC - DO NOT EDIT */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "nnc_types.h"
#include "model.h"

int main(void) {{
    printf("NNC Model Runner\\n");
    printf("================\\n");

    /* Setup all tensors */
{setup_code}
{print_code}

    /* Free memory */
{frees_code}

    printf("\\nInference complete.\\n");
    return 0;
}}
"""

    def _assign_symbols(self, ctx: CompileContext):
        """Assign C symbol names using NameManager."""
        name_manager = NameManager()

        # Assign names for tensors
        for tensor_name, tensor in ctx.graph.tensors.items():
            # Use NameManager to sanitize the name
            c_name = name_manager.get_symbol(tensor_name, prefix="tensor_")
            ctx.tensor_symbols[tensor_name] = c_name

        # Assign names for nodes
        for node_name in ctx.graph.nodes:
            c_name = name_manager.get_symbol(node_name, prefix="node_")
            ctx.node_symbols[node_name] = c_name

    def _map_dtype(self, dtype: DataType) -> str:
        """Map IR dtype to C dtype."""
        mapping = {
            DataType.FLOAT32: "float",
            DataType.FLOAT16: "uint16_t",
            DataType.INT32: "int32_t",
            DataType.INT8: "int8_t",
            DataType.UINT8: "uint8_t",
            DataType.BOOL: "uint8_t",
        }
        return mapping.get(dtype, "float")

    def _map_numpy_dtype(self, np_dtype) -> str:
        """Map numpy dtype to C dtype."""
        import numpy as np

        if np_dtype == np.float32:
            return "float"
        elif np_dtype == np.float16:
            return "uint16_t"
        elif np_dtype == np.int32:
            return "int32_t"
        elif np_dtype == np.int8:
            return "int8_t"
        elif np_dtype == np.uint8:
            return "uint8_t"
        else:
            return "float"
