"""x86 backend for simulation."""

from nnc_py.codegen.base import BackendBase, CodeGenResult
from nnc_py.codegen.c_emitter import CEmitter
from nnc_py.ir.context import CompileContext
from nnc_py.ir.types import DataType


class X86Backend(BackendBase):
    """x86 target backend - generates code for simulation."""

    def generate(self, ctx: CompileContext) -> CodeGenResult:
        """Generate x86 C code."""
        result = CodeGenResult()

        # Assign C symbol names
        self._assign_symbols(ctx)

        # Generate header file
        header = self._generate_header(ctx)
        result.add_file("model.h", header, "header")

        # Generate source file
        source = self._generate_source(ctx)
        result.add_file("model.c", source, "source")

        # Generate constants data file
        if ctx.graph.constants:
            constants = self._generate_constants(ctx)
            result.add_file("constants.c", constants, "source")

        # Generate Makefile
        makefile = self._generate_makefile(ctx)
        result.add_file("Makefile", makefile, "build")

        # Generate test runner
        test_runner = self._generate_test_runner(ctx)
        result.add_file("test_runner.c", test_runner, "source")

        return result

    def _generate_source(self, ctx: CompileContext) -> str:
        """Generate main source file."""
        emitter = CEmitter()
        return emitter.emit(ctx)

    def _generate_header(self, ctx: CompileContext) -> str:
        """Generate header file."""
        lines = [
            "/* Auto-generated by NTC - DO NOT EDIT */",
            "#ifndef MODEL_H",
            "#define MODEL_H",
            "",
            "#include <stdint.h>",
            "",
            "/* Input/Output declarations */",
        ]

        for tensor_name in ctx.graph.inputs:
            tensor = ctx.graph.get_tensor(tensor_name)
            c_dtype = self._map_dtype(tensor.dtype)
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            lines.append(f"extern {c_dtype} *{var_name};")

        for tensor_name in ctx.graph.outputs:
            tensor = ctx.graph.get_tensor(tensor_name)
            c_dtype = self._map_dtype(tensor.dtype)
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            lines.append(f"extern {c_dtype} *{var_name};")

        lines.extend([
            "",
            "/* Main inference function */",
            "void nnc_run(void);",
            "",
            "#endif  // MODEL_H",
        ])

        return "\n".join(lines)

    def _generate_constants(self, ctx: CompileContext) -> str:
        """Generate constants data file."""
        lines = [
            "/* Auto-generated by NNC - DO NOT EDIT */",
            '#include "nnc_runtime.h"',
            "",
        ]

        import numpy as np

        for name, arr in ctx.graph.constants.items():
            dtype = self._map_numpy_dtype(arr.dtype)
            size = arr.size
            data = arr.flatten().tolist()

            # Format data
            data_str = ", ".join(str(x) for x in data[:10])
            if size > 10:
                data_str += ", ..."

            lines.append(f"/* Constant: {name} */")
            lines.append(f"const {dtype} {name}[{size}] = {{")
            lines.append(f"    {data_str}")
            lines.append("};")
            lines.append("")

        return "\n".join(lines)

    def _generate_makefile(self, ctx: CompileContext) -> str:
        """Generate Makefile."""
        return """# Auto-generated by NNC - DO NOT EDIT
CC = gcc
CFLAGS = -std=c11 -O2 -Wall -Wextra -I./runtime/include
LDFLAGS = -L./runtime/x86 -lnnc_x86 -lm

.PHONY: all clean run

all: model

model: model.o constants.o test_runner.o
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f *.o model

run: model
	./model
"""

    def _generate_test_runner(self, ctx: CompileContext) -> str:
        """Generate test runner."""
        return """/* Auto-generated by NNC - DO NOT EDIT */
#include <stdio.h>
#include <stdlib.h>
#include "model.h"

int main(void) {
    printf("NNC Model Runner\\n");
    printf("================\\n");

    // TODO: Allocate and initialize input tensors
    // TODO: Call nnc_run()
    // TODO: Verify output tensors

    printf("Inference complete.\\n");
    return 0;
}
"""

    def _assign_symbols(self, ctx: CompileContext):
        """Assign C symbol names."""
        for tensor_name, tensor in ctx.graph.tensors.items():
            # Replace invalid C characters with underscore
            c_name = tensor_name.replace("/", "_").replace(".", "_")
            ctx.tensor_symbols[tensor_name] = c_name

        for node_name in ctx.graph.nodes:
            c_name = f"node_{node_name.replace('/', '_').replace('.', '_')}"
            ctx.node_symbols[node_name] = c_name

    def _map_dtype(self, dtype: DataType) -> str:
        """Map IR dtype to C dtype."""
        mapping = {
            DataType.FLOAT32: "float",
            DataType.FLOAT16: "uint16_t",
            DataType.INT32: "int32_t",
            DataType.INT8: "int8_t",
            DataType.UINT8: "uint8_t",
            DataType.BOOL: "uint8_t",
        }
        return mapping.get(dtype, "float")

    def _map_numpy_dtype(self, np_dtype) -> str:
        """Map numpy dtype to C dtype."""
        import numpy as np

        if np_dtype == np.float32:
            return "float"
        elif np_dtype == np.float16:
            return "uint16_t"
        elif np_dtype == np.int32:
            return "int32_t"
        elif np_dtype == np.int8:
            return "int8_t"
        elif np_dtype == np.uint8:
            return "uint8_t"
        else:
            return "float"
