"""x86 backend for simulation."""

from typing import List

import numpy as np

from nnc_py.codegen.base import BackendBase, CodeGenResult
from nnc_py.codegen.c_emitter import CEmitter
from nnc_py.ir.context import CompileContext
from nnc_py.ir.node import OpType
from nnc_py.ir.types import DataType
from nnc_py.utils.name_manager import NameManager


class X86Backend(BackendBase):
    """x86 target backend - generates code for simulation."""

    def generate(self, ctx: CompileContext) -> CodeGenResult:
        """Generate x86 C code."""
        result = CodeGenResult()

        # Assign C symbol names
        self._assign_symbols(ctx)

        # Generate header file
        header = self._generate_header(ctx)
        result.add_file("model.h", header, "header")

        # Generate source file
        source = self._generate_source(ctx)
        result.add_file("model.c", source, "source")

        # Generate tensors definition file
        tensors = self._generate_tensors(ctx)
        result.add_file("tensors.c", tensors, "source")

        # Generate constants data file
        if ctx.graph.constants:
            constants = self._generate_constants(ctx)
            result.add_file("constants.c", constants, "source")

        # Generate Makefile
        makefile = self._generate_makefile(ctx)
        result.add_file("Makefile", makefile, "build")

        # Generate test runner
        test_runner = self._generate_test_runner(ctx)
        result.add_file("test_runner.c", test_runner, "source")

        return result

    def _generate_source(self, ctx: CompileContext) -> str:
        """Generate main source file with spill/reload support."""
        from nnc_py.codegen.c_emitter import CEmitter
        from nnc_py.passes.memory_planning import get_memory_allocation_plan
        from nnc_py.passes.spill import get_spill_plan
        from nnc_py.passes.unified_memory import get_unified_memory_plan

        # Check for new MemoryAllocationPlan first
        alloc_plan = get_memory_allocation_plan(ctx)

        # Check for unified memory plan (legacy)
        unified_plan = None
        if alloc_plan is None and "unified_memory_plan" in ctx.metadata:
            try:
                unified_plan = get_unified_memory_plan(ctx)
            except RuntimeError:
                pass

        # Check for legacy spill plan
        spill_plan = get_spill_plan(ctx)

        # Determine which plan to use
        if alloc_plan is not None and alloc_plan.has_spill:
            # Use new MemoryAllocationPlan with reload code generation
            return self._generate_source_with_unified_spill(ctx, alloc_plan)
        elif unified_plan is not None and unified_plan.has_spill:
            # Use legacy unified memory plan
            return self._generate_source_with_unified_spill(ctx, unified_plan)
        elif spill_plan is not None and spill_plan.has_overflow:
            # Use legacy spill plan
            return self._generate_source_with_spill(ctx, spill_plan)
        else:
            # No overflow, use standard emitter
            emitter = CEmitter()
            return emitter.emit(ctx)

    def _generate_source_with_spill(self, ctx: CompileContext, spill_plan) -> str:
        """Generate source file with spill/reload wrapper functions."""
        from nnc_py.codegen.c_emitter import CEmitter

        lines = [
            "/* Auto-generated by NNC - DO NOT EDIT */",
            "",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            '#include "model.h"',
            '#include "nnc_ops.h"',
            "",
            "/* External memory pools (defined in tensors.c) */",
            "extern uint8_t _nnc_fast_pool[];",
            "extern uint8_t _nnc_slow_pool[];",
            "",
            "/* Forward declarations for spill/reload functions */",
        ]

        # Generate forward declarations for node functions
        nodes = ctx.graph.topological_sort()
        for node in nodes:
            if node.op_type == OpType.CONSTANT:
                continue
            func_name = ctx.node_symbols.get(node.name, node.name)
            lines.append(f"static void {func_name}_body(void);")

        lines.append("")
        lines.append("/* Spill/Reload wrapper functions */")

        # Generate wrapper functions with spill/reload
        spill_plan_dict = {
            (p.tensor_name, p.after_node): p
            for p in spill_plan.spill_points
        }
        reload_plan_dict = {
            (p.tensor_name, p.before_node): p
            for p in spill_plan.reload_points
        }

        for node in nodes:
            if node.op_type == OpType.CONSTANT:
                continue

            func_name = ctx.node_symbols.get(node.name, node.name)

            # Collect spills after this node
            spills_after = [
                p for p in spill_plan.spill_points if p.after_node == node.name
            ]

            # Collect reloads before this node
            reloads_before = [
                p for p in spill_plan.reload_points if p.before_node == node.name
            ]

            lines.append(f"/* {func_name}: {node.op_type.value} */")
            lines.append(f"static void {func_name}(void) {{")

            # Reload before node
            for reload in reloads_before:
                lines.extend([
                    f"    /* Reload {reload.tensor_name} from slow memory */",
                    f"    memcpy(",
                    f"        _nnc_fast_pool + {reload.to_fast_offset},",
                    f"        _nnc_slow_pool + {reload.from_slow_offset},",
                    f"        {reload.size}",
                    f"    );",
                    "",
                ])

            # Call the body
            lines.append(f"    {func_name}_body();")

            # Spill after node
            for spill in spills_after:
                lines.extend([
                    "",
                    f"    /* Spill {spill.tensor_name} to slow memory */",
                    f"    memcpy(",
                    f"        _nnc_slow_pool + {spill.to_slow_offset},",
                    f"        _nnc_fast_pool + {spill.from_fast_offset},",
                    f"        {spill.size}",
                    f"    );",
                ])

            lines.append("}")
            lines.append("")

        lines.append("/* Node body functions */")

        # Generate body functions (using standard emitter)
        emitter = CEmitter()
        body_code = emitter.emit(ctx)

        # We need to modify the body_code to rename functions to _body
        # and remove the main entry point
        lines.append(self._process_body_code(body_code, ctx))

        # Generate main entry point
        lines.append("")
        lines.append("/* Main inference entry point */")
        lines.append("void nnc_run(void) {")

        for node in nodes:
            if node.op_type == OpType.CONSTANT:
                continue
            func_name = ctx.node_symbols.get(node.name, node.name)
            lines.append(f"    {func_name}();")

        lines.append("}")

        return "\n".join(lines)

    def _process_body_code(self, body_code: str, ctx: CompileContext) -> str:
        """Process the body code from CEmitter."""
        lines = body_code.split("\n")
        output = []
        skip_main = False

        for line in lines:
            # Skip the includes (we already added them)
            if line.startswith("#include") or line.startswith("/* Auto-generated"):
                continue

            # Skip the main nnc_run function (we'll generate our own)
            if "void nnc_run(void)" in line:
                skip_main = True
                continue

            if skip_main:
                if line.startswith("}"):
                    skip_main = False
                continue

            # Rename functions to _body
            for node_name, func_name in ctx.node_symbols.items():
                if f"void {func_name}(void)" in line:
                    line = line.replace(f"void {func_name}(void)", f"static void {func_name}_body(void)")

            output.append(line)

        return "\n".join(output)

    def _generate_source_with_unified_spill(self, ctx: CompileContext, plan) -> str:
        """Generate source file with spill/reload wrapper functions using UnifiedMemoryPlan.

        The key requirement: ALL operators must execute with inputs/outputs in fast memory.
        When tensors are spilled to slow memory, they must be:
        1. Reloaded to fast memory before operator execution
        2. Used via temp Tensor structs pointing to fast memory
        3. Spilled back to slow memory after operator execution
        """
        from nnc_py.codegen.c_emitter import CEmitter

        lines = [
            "/* Auto-generated by NNC - DO NOT EDIT */",
            "",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            '#include "model.h"',
            '#include "nnc_ops.h"',
            "",
            "/* External memory pools (defined in tensors.c) */",
            "extern uint8_t _nnc_fast_pool[];",
            "extern uint8_t _nnc_slow_pool[];",
            "",
        ]

        # Calculate reload buffer requirements
        # Need buffers for:
        # 1. Inputs to reload
        # 2. Outputs that are spilled (need temp buffers in fast memory)
        max_reload_slots = plan.get_max_reload_slots()

        # Count max total buffers needed at any node (inputs + spilled outputs)
        nodes = ctx.graph.topological_sort()
        max_total_slots = 0
        for node in nodes:
            if node.op_type == OpType.CONSTANT:
                continue
            node_idx = next(i for i, n in enumerate(nodes) if n == node)

            # Count inputs that need reload
            reloads_before = plan.get_reload_points_before(node_idx)
            input_slots = len(reloads_before)

            # Count outputs that are spilled (need temp buffers)
            output_slots = sum(
                1 for o in node.outputs
                if plan.tensor_allocations.get(o) and plan.tensor_allocations.get(o).is_spilled
            )

            max_total_slots = max(max_total_slots, input_slots + output_slots)

        # Use the larger of the two calculations
        max_reload_slots = max(max_reload_slots, max_total_slots)

        spilled_tensors = plan.spilled_tensors

        # Get max tensor size for reload buffer sizing
        max_tensor_size = 0
        for tensor_name, alloc in plan.tensor_allocations.items():
            if alloc.is_spilled:
                max_tensor_size = max(max_tensor_size, alloc.size)

        # If no spilled tensors, fall back to standard emitter
        if not spilled_tensors:
            emitter = CEmitter()
            return emitter.emit(ctx)

        # Generate reload buffers in fast memory
        if max_reload_slots > 0 and max_tensor_size > 0:
            lines.append("/* Reload buffers in fast memory for spilled tensors */")
            lines.append(f"/* Max reload slots: {max_reload_slots}, Slot size: {max_tensor_size} */")
            for i in range(max_reload_slots):
                lines.append(f"static uint8_t _nnc_reload_buffer_{i}[{max_tensor_size}];")
            lines.append("")

        # Generate forward declarations for node functions (only for those without spill/reload)
        nodes = ctx.graph.topological_sort()
        for node in nodes:
            if node.op_type == OpType.CONSTANT:
                continue

            func_name = ctx.node_symbols.get(node.name, node.name)
            node_idx = next(i for i, n in enumerate(nodes) if n == node)

            # Check if this node needs spill/reload
            has_spill = len(plan.get_spill_points_after(node_idx)) > 0
            has_reload = len(plan.get_reload_points_before(node_idx)) > 0
            has_spilled_output = any(
                plan.tensor_allocations.get(o) and plan.tensor_allocations.get(o).is_spilled
                for o in node.outputs
            )

            # Only declare _body if no spill/reload needed
            if not has_spill and not has_reload and not has_spilled_output:
                lines.append(f"static void {func_name}_body(void);")

        lines.append("")
        lines.append("/* Spill/Reload wrapper functions */")

        # Generate wrapper functions with spill/reload
        for node in nodes:
            if node.op_type == OpType.CONSTANT:
                continue

            func_name = ctx.node_symbols.get(node.name, node.name)
            node_idx = next(i for i, n in enumerate(nodes) if n == node)

            # Collect spills after this node
            spills_after = plan.get_spill_points_after(node_idx)

            # Collect reloads before this node
            reloads_before = plan.get_reload_points_before(node_idx)

            # Determine which inputs need reload (have reload points before this node)
            inputs_need_reload = {rp.tensor_name: rp for rp in reloads_before}

            # Also check if any input tensors are spilled (allocated in slow memory)
            # This handles model inputs that happen to be in slow memory
            additional_inputs = []
            for input_name in node.inputs:
                if input_name in inputs_need_reload:
                    continue  # Already has a reload point
                alloc = plan.tensor_allocations.get(input_name)
                if alloc and alloc.is_spilled:
                    # Input is spilled but no reload point - create a synthetic one
                    from nnc_py.passes.memory_strategy import ReloadPoint
                    additional_inputs.append((input_name, alloc))
                    inputs_need_reload[input_name] = ReloadPoint(
                        tensor_name=input_name,
                        before_node=node.name,
                        before_node_idx=node_idx,
                        from_slow_offset=alloc.offset,
                        to_buffer_id=alloc.buffer_id,
                        to_fast_offset=0,
                        size=alloc.size,
                        reload_slot_id=-1,  # Will assign below
                    )

            # Assign slot IDs to synthetic reload points
            current_slot = max([rp.reload_slot_id for rp in inputs_need_reload.values()], default=-1) + 1
            for input_name, _ in additional_inputs:
                inputs_need_reload[input_name].reload_slot_id = current_slot
                current_slot += 1

            # Determine which outputs need temp tensors
            # An output needs a temp tensor if:
            # 1. It's spilled (allocated in slow memory), OR
            # 2. There's a spill point after this node for it
            outputs_need_temp = {}
            for output_name in node.outputs:
                alloc = plan.tensor_allocations.get(output_name)
                if alloc and alloc.is_spilled:
                    # Output lives in slow memory - need temp tensor
                    # Find the spill point for this output
                    sp = next((s for s in spills_after if s.tensor_name == output_name), None)
                    if sp:
                        outputs_need_temp[output_name] = sp
                    else:
                        # Create a synthetic spill point for temp allocation
                        from nnc_py.passes.memory_strategy import SpillPoint
                        outputs_need_temp[output_name] = SpillPoint(
                            tensor_name=output_name,
                            after_node=node.name,
                            after_node_idx=node_idx,
                            from_buffer_id=alloc.buffer_id,
                            from_fast_offset=0,
                            to_slow_offset=alloc.offset,
                            size=alloc.size,
                        )

            lines.append(f"/* {func_name}: {node.op_type.value} */")
            lines.append(f"static void {func_name}(void) {{")

            # Declare temp tensors for spilled inputs
            temp_tensor_decls = []
            for input_name in node.inputs:
                if input_name in inputs_need_reload:
                    rp = inputs_need_reload[input_name]
                    temp_name = f"temp_{ctx.tensor_symbols.get(input_name, input_name)}"
                    slot_id = rp.reload_slot_id
                    temp_tensor_decls.append((temp_name, slot_id, input_name, rp.size, 'input'))

            # Declare temp tensors for spilled outputs
            output_slot_idx = len(inputs_need_reload)
            for output_name in node.outputs:
                if output_name in outputs_need_temp:
                    sp = outputs_need_temp[output_name]
                    temp_name = f"temp_{ctx.tensor_symbols.get(output_name, output_name)}"
                    slot_id = output_slot_idx
                    temp_tensor_decls.append((temp_name, slot_id, output_name, sp.size, 'output'))
                    output_slot_idx += 1

            # Generate temp tensor declarations
            if temp_tensor_decls:
                lines.append("    /* Temp tensors pointing to fast memory */")
                for temp_name, slot_id, orig_name, size, _ in temp_tensor_decls:
                    lines.append(f"    static Tensor {temp_name};")

            # Reload spilled inputs to fast memory
            for input_name in node.inputs:
                if input_name in inputs_need_reload:
                    rp = inputs_need_reload[input_name]
                    temp_name = f"temp_{ctx.tensor_symbols.get(input_name, input_name)}"
                    var_name = ctx.tensor_symbols.get(input_name, input_name)
                    lines.extend([
                        f"    /* Reload {input_name} from slow to fast memory */",
                        f"    memcpy(_nnc_reload_buffer_{rp.reload_slot_id},",
                        f"           _nnc_slow_pool + {rp.from_slow_offset}, {rp.size});",
                        f"    {temp_name}.data = _nnc_reload_buffer_{rp.reload_slot_id};",
                        f"    {temp_name}.dtype = {var_name}.dtype;",
                        f"    {temp_name}.shape = {var_name}.shape;",
                        f"    {temp_name}.ndim = {var_name}.ndim;",
                        f"    {temp_name}.nbytes = {rp.size};",
                        "",
                    ])

            # Setup temp outputs
            output_slot_idx = len(inputs_need_reload)
            for output_name in node.outputs:
                if output_name in outputs_need_temp:
                    sp = outputs_need_temp[output_name]
                    temp_name = f"temp_{ctx.tensor_symbols.get(output_name, output_name)}"
                    var_name = ctx.tensor_symbols.get(output_name, output_name)
                    # Get the slot_id from temp_tensor_decls
                    slot_id = next((s for tn, s, _, _, _ in temp_tensor_decls if tn == temp_name), output_slot_idx)
                    lines.extend([
                        f"    /* Setup temp output for {output_name} */",
                        f"    {temp_name}.data = _nnc_reload_buffer_{slot_id};",
                        f"    {temp_name}.dtype = {var_name}.dtype;",
                        f"    {temp_name}.shape = {var_name}.shape;",
                        f"    {temp_name}.ndim = {var_name}.ndim;",
                        f"    {temp_name}.nbytes = {sp.size};",
                        "",
                    ])

            # Generate operator call with potentially swapped arguments
            lines.append("    /* Execute operator in fast memory */")
            op_call = self._generate_operator_call_with_temps(
                ctx, node, inputs_need_reload, outputs_need_temp
            )
            lines.append(f"    {op_call}")

            # Spill outputs back to slow memory
            output_slot_idx = len(inputs_need_reload)
            for output_name in node.outputs:
                if output_name in outputs_need_temp:
                    sp = outputs_need_temp[output_name]
                    temp_name = f"temp_{ctx.tensor_symbols.get(output_name, output_name)}"
                    # Get the slot_id from temp_tensor_decls
                    slot_id = next((s for tn, s, _, _, _ in temp_tensor_decls if tn == temp_name), output_slot_idx)
                    lines.extend([
                        "",
                        f"    /* Spill {output_name} from fast to slow memory */",
                        f"    memcpy(_nnc_slow_pool + {sp.to_slow_offset},",
                        f"           _nnc_reload_buffer_{slot_id}, {sp.size});",
                    ])

            lines.append("}")
            lines.append("")

        # Generate body functions for nodes without spill/reload
        lines.append("/* Node body functions (no spill/reload needed) */")

        # Generate operator calls for all nodes (for reference)
        # We generate simplified versions that don't need spill/reload
        for node in nodes:
            if node.op_type == OpType.CONSTANT:
                continue

            func_name = ctx.node_symbols.get(node.name, node.name)
            node_idx = next(i for i, n in enumerate(nodes) if n == node)

            # Check if this node needs spill/reload
            # A node needs spill/reload wrapper if:
            # 1. It has reload points before it (inputs to reload), OR
            # 2. Any of its outputs are spilled (live in slow memory)
            has_spill = len(plan.get_spill_points_after(node_idx)) > 0
            has_reload = len(plan.get_reload_points_before(node_idx)) > 0
            has_spilled_output = any(
                plan.tensor_allocations.get(o) and plan.tensor_allocations.get(o).is_spilled
                for o in node.outputs
            )

            if not has_spill and not has_reload and not has_spilled_output:
                # No spill/reload needed, generate standard operator call
                lines.append(f"/* {func_name}: {node.op_type.value} */")
                lines.append(f"static void {func_name}_body(void) {{")
                op_call = self._generate_operator_call(ctx, node, use_temps=False)
                lines.append(f"    {op_call}")
                lines.append("}")
                lines.append("")
            else:
                # Has spill/reload, don't generate _body function
                # The wrapper handles everything
                pass

        # Generate main entry point
        lines.append("")
        lines.append("/* Main inference entry point */")
        lines.append("void nnc_run(void) {")

        for node in nodes:
            if node.op_type == OpType.CONSTANT:
                continue
            func_name = ctx.node_symbols.get(node.name, node.name)
            lines.append(f"    {func_name}();")

        lines.append("}")

        return "\n".join(lines)

    def _generate_operator_call_with_temps(
        self,
        ctx: CompileContext,
        node: "Node",
        inputs_need_reload: dict,
        outputs_need_temp: dict,
    ) -> str:
        """Generate operator call using temp tensors for spilled inputs/outputs.

        Args:
            ctx: Compilation context
            node: Node to generate call for
            inputs_need_reload: Map of input_name -> ReloadPoint
            outputs_need_temp: Map of output_name -> SpillPoint (for spilled outputs)

        Returns:
            C code line for the operator call
        """
        op_name = f"nnc_{node.op_type.value.lower()}"
        args = []

        # Input tensors
        for input_name in node.inputs:
            var_name = ctx.tensor_symbols.get(input_name, input_name)
            if input_name in inputs_need_reload:
                # Use temp tensor
                temp_name = f"temp_{var_name}"
                args.append(f"&{temp_name}")
            else:
                # Use original tensor
                args.append(f"&{var_name}")

        # Output tensors
        for output_name in node.outputs:
            var_name = ctx.tensor_symbols.get(output_name, output_name)
            if output_name in outputs_need_temp:
                # Use temp tensor
                temp_name = f"temp_{var_name}"
                args.append(f"&{temp_name}")
            else:
                # Use original tensor
                args.append(f"&{var_name}")

        # Add operation-specific attributes
        if node.op_type == OpType.CONV2D:
            kernel_shape = node.attrs.get("kernel_shape", [1, 1])
            strides = node.attrs.get("strides", [1, 1])
            pads = node.attrs.get("pads", [0, 0])
            args.extend([str(kernel_shape[0]), str(kernel_shape[1])])
            args.extend([str(strides[0]), str(strides[1])])
            if len(pads) == 4:
                args.append(str(pads[0]))
                args.append(str(pads[1]))
            elif len(pads) == 2:
                args.extend([str(pads[0]), str(pads[1])])
            else:
                args.extend(["0", "0"])
        elif node.op_type == OpType.LAYER_NORM:
            axis = node.attrs.get("axis", -1)
            epsilon = node.attrs.get("epsilon", 1e-5)
            args.append(f"{axis}")
            args.append(f"{epsilon}f")
        elif node.op_type == OpType.REDUCE_MEAN:
            axis = node.attrs.get("axis", None)
            keepdims = node.attrs.get("keepdims", 1)
            if axis is not None:
                args.append(str(axis))
                args.append(str(keepdims))
        elif node.op_type == OpType.GEMM:
            # Gemm has optional bias (3rd input), need to add attributes
            # nnc_gemm(Tensor* a, Tensor* b, Tensor* c, Tensor* output,
            #          float alpha, float beta, int trans_a, int trans_b)
            # Check if bias (C) is present
            if len(node.inputs) < 3:
                # No bias tensor, insert NULL
                args.insert(2, "NULL")
            # Add attributes
            alpha = node.attrs.get("alpha", 1.0)
            beta = node.attrs.get("beta", 1.0)
            trans_a = node.attrs.get("transA", 0)
            trans_b = node.attrs.get("transB", 0)
            args.append(f"{alpha}f")
            args.append(f"{beta}f")
            args.append(str(trans_a))
            args.append(str(trans_b))

        return f"{op_name}({', '.join(args)});"

    def _generate_operator_call(self, ctx: CompileContext, node: "Node", use_temps: bool = False) -> str:
        """Generate operator call (for non-spill nodes).

        Args:
            ctx: Compilation context
            node: Node to generate call for
            use_temps: Whether to use temp tensors (not used here, for compatibility)

        Returns:
            C code line for the operator call
        """
        op_name = f"nnc_{node.op_type.value.lower()}"
        args = []

        # Input tensors
        for input_name in node.inputs:
            var_name = ctx.tensor_symbols.get(input_name, input_name)
            args.append(f"&{var_name}")

        # Output tensors
        for output_name in node.outputs:
            var_name = ctx.tensor_symbols.get(output_name, output_name)
            args.append(f"&{var_name}")

        # Add operation-specific attributes
        if node.op_type == OpType.CONV2D:
            kernel_shape = node.attrs.get("kernel_shape", [1, 1])
            strides = node.attrs.get("strides", [1, 1])
            pads = node.attrs.get("pads", [0, 0])
            args.extend([str(kernel_shape[0]), str(kernel_shape[1])])
            args.extend([str(strides[0]), str(strides[1])])
            if len(pads) == 4:
                args.append(str(pads[0]))
                args.append(str(pads[1]))
            elif len(pads) == 2:
                args.extend([str(pads[0]), str(pads[1])])
            else:
                args.extend(["0", "0"])
        elif node.op_type == OpType.LAYER_NORM:
            axis = node.attrs.get("axis", -1)
            epsilon = node.attrs.get("epsilon", 1e-5)
            args.append(f"{axis}")
            args.append(f"{epsilon}f")
        elif node.op_type == OpType.REDUCE_MEAN:
            axis = node.attrs.get("axis", None)
            keepdims = node.attrs.get("keepdims", 1)
            if axis is not None:
                args.append(str(axis))
                args.append(str(keepdims))
        elif node.op_type == OpType.GEMM:
            # Gemm has optional bias (3rd input), need to add attributes
            # nnc_gemm(Tensor* a, Tensor* b, Tensor* c, Tensor* output,
            #          float alpha, float beta, int trans_a, int trans_b)
            # Check if bias (C) is present
            if len(node.inputs) < 3:
                # No bias tensor, insert NULL
                args.insert(2, "NULL")
            # Add attributes
            alpha = node.attrs.get("alpha", 1.0)
            beta = node.attrs.get("beta", 1.0)
            trans_a = node.attrs.get("transA", 0)
            trans_b = node.attrs.get("transB", 0)
            args.append(f"{alpha}f")
            args.append(f"{beta}f")
            args.append(str(trans_a))
            args.append(str(trans_b))

        return f"{op_name}({', '.join(args)});"

    def _generate_header(self, ctx: CompileContext) -> str:
        """Generate header file."""
        lines = [
            "/* Auto-generated by NTC - DO NOT EDIT */",
            "#ifndef MODEL_H",
            "#define MODEL_H",
            "",
            "#include <stdint.h>",
            '#include "nnc_types.h"',
            "",
            "/* Tensor declarations */",
        ]

        # Declare all non-constant tensors
        for tensor_name in ctx.graph.inputs:
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            lines.append(f"extern Tensor {var_name};")

        for tensor_name, tensor in ctx.graph.tensors.items():
            if tensor_name in ctx.graph.inputs or tensor_name in ctx.graph.constants:
                continue
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            lines.append(f"extern Tensor {var_name};")

        for tensor_name in ctx.graph.outputs:
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            if f"extern Tensor {var_name};" not in lines:
                lines.append(f"extern Tensor {var_name};")

        # Declare constant tensors (defined in constants.c)
        for tensor_name in ctx.graph.constants:
            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            if f"extern Tensor {var_name};" not in lines:
                lines.append(f"extern Tensor {var_name};")

        # Declare constant data arrays for use in shape operations
        import numpy as np
        for tensor_name, arr in ctx.graph.constants.items():
            # Only declare INT64 arrays (used for shapes)
            if arr.dtype == np.int64 or arr.dtype == np.int32:
                var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
                dtype = "int64_t" if arr.dtype == np.int64 else "int32_t"
                size = arr.size
                lines.append(f"extern const {dtype} {var_name}_data[{size}];")

        lines.extend([
            "",
            "/* Main inference function */",
            "void nnc_run(void);",
            "",
            "#endif  // MODEL_H",
        ])

        return "\n".join(lines)

    def _generate_constants(self, ctx: CompileContext) -> str:
        """Generate constants data file."""
        lines = [
            "/* Auto-generated by NNC - DO NOT EDIT */",
            '#include "nnc_runtime.h"',
            "",
        ]

        import numpy as np

        for name, arr in ctx.graph.constants.items():
            tensor = ctx.graph.get_tensor(name)
            # Get correct dtype based on array type
            dtype, element_size, nnc_dtype = self._get_constant_type_info(arr)
            size = arr.size
            data = arr.flatten().tolist()
            shape = list(arr.shape)

            # Use sanitized C symbol name
            var_name = ctx.tensor_symbols.get(name, name)

            # For INT64/INT32 constants (used as shapes), make data array non-static
            # so it can be accessed from model.c for reshape operations
            is_shape_constant = (arr.dtype == np.int64 or arr.dtype == np.int32)
            storage_class = "" if is_shape_constant else "static "

            lines.append(f"/* Constant: {name} */")
            lines.append(f"{storage_class}const {dtype} {var_name}_data[{size}] = {{")

            # Format data with multiple values per line
            values_per_line = 10
            for i in range(0, size, values_per_line):
                chunk = data[i:i + values_per_line]
                if dtype == "float":
                    line_values = ", ".join(f"{x:.9g}" for x in chunk)
                else:
                    # Integer types - format as integers
                    line_values = ", ".join(f"{int(x)}" for x in chunk)
                if i + values_per_line < size:
                    line_values += ","
                lines.append(f"    {line_values}")

            lines.append("};")
            lines.append("")

            # Generate Tensor structure
            shape_str = ", ".join(str(s) for s in shape)
            lines.append(f"static const int64_t {var_name}_shape[] = {{{shape_str}}};")
            lines.append(f"Tensor {var_name} = {{")
            lines.append(f"    .data = (void*){var_name}_data,")
            lines.append(f"    .dtype = {nnc_dtype},")
            lines.append(f"    .shape = (int64_t*){var_name}_shape,")
            lines.append(f"    .ndim = {len(shape)},")
            lines.append(f"    .nbytes = {size * element_size},")
            lines.append("};")
            lines.append("")

        return "\n".join(lines)

    def _get_constant_type_info(self, arr: np.ndarray) -> tuple[str, int, str]:
        """Get C type, element size, and NNC dtype enum for a constant array.

        Returns:
            Tuple of (c_dtype, element_size, nnc_dtype_enum)
        """
        import numpy as np

        if arr.dtype == np.float32:
            return "float", 4, "NNC_DTYPE_FLOAT32"
        elif arr.dtype == np.float64:
            return "double", 8, "NNC_DTYPE_FLOAT32"
        elif arr.dtype == np.float16:
            return "uint16_t", 2, "NNC_DTYPE_FLOAT16"
        elif arr.dtype == np.int64:
            return "int64_t", 8, "NNC_DTYPE_INT64"
        elif arr.dtype == np.int32:
            return "int32_t", 4, "NNC_DTYPE_INT32"
        elif arr.dtype == np.int8:
            return "int8_t", 1, "NNC_DTYPE_INT8"
        elif arr.dtype == np.uint8:
            return "uint8_t", 1, "NNC_DTYPE_UINT8"
        elif arr.dtype == np.bool_:
            return "uint8_t", 1, "NNC_DTYPE_BOOL"
        else:
            # Default to float32
            return "float", 4, "NNC_DTYPE_FLOAT32"

    def _generate_makefile(self, ctx: CompileContext) -> str:
        """Generate Makefile."""
        has_constants = bool(ctx.graph.constants)
        objs = "model.o tensors.o"
        if has_constants:
            objs += " constants.o"
        objs += " test_runner.o ops.o"

        # Determine runtime path relative to the output directory
        # For installed package: use NNC_RUNTIME_PATH env var
        # For development: relative path from output to project root
        return f"""# Auto-generated by NNC - DO NOT EDIT
# Set NNC_RUNTIME_PATH to point to the runtime directory if not in dev tree
CC = gcc
CFLAGS = -std=c11 -O2 -Wall -Wextra
LDFLAGS = -lm

# Runtime include path - can be overridden by environment
NNC_RUNTIME ?= ../../runtime
CFLAGS += -I$(NNC_RUNTIME)/include

.PHONY: all clean run

all: model

model: {objs}
\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

ops.o:
\t$(CC) $(CFLAGS) -c $(NNC_RUNTIME)/x86/ops.c

%.o: %.c
\t$(CC) $(CFLAGS) -c $<

clean:
\trm -f *.o model

run: model
\t./model
"""

    def _generate_tensors(self, ctx: CompileContext) -> str:
        """Generate tensors definition file."""
        lines = [
            "/* Auto-generated by NNC - DO NOT EDIT */",
            '#include "nnc_types.h"',
            "",
        ]

        # Check for new memory allocation plan
        from nnc_py.passes.memory_planning import get_memory_allocation_plan
        alloc_plan = get_memory_allocation_plan(ctx)

        # Check for unified memory plan (legacy)
        from nnc_py.passes.unified_memory import get_unified_memory_plan
        unified_plan = None
        if "unified_memory_plan" in ctx.metadata:
            try:
                unified_plan = get_unified_memory_plan(ctx)
            except RuntimeError:
                pass

        # Determine if we have spill
        has_spill = alloc_plan is not None and alloc_plan.has_spill
        if not has_spill and unified_plan is not None:
            has_spill = unified_plan.has_spill

        # Also check if any tensors are allocated in slow memory
        has_slow_memory_tensors = False
        if alloc_plan is not None:
            has_slow_memory_tensors = any(
                alloc.is_spilled for alloc in alloc_plan.tensor_allocations.values()
            )
        elif unified_plan is not None:
            has_slow_memory_tensors = any(
                alloc.in_slow_memory for alloc in unified_plan.tensor_allocations.values()
            )

        # Generate slow pool if we have spill points OR slow memory tensors
        needs_slow_pool = has_spill or has_slow_memory_tensors

        # Check if memory planning was performed
        has_memory_plan = alloc_plan is not None or unified_plan is not None or "memory_plan" in ctx.metadata

        if has_memory_plan:
            # Generate static memory pool(s)
            lines.extend(self._generate_memory_pool(ctx))
            lines.append("")

        # Determine which pool names to use
        if has_spill:
            fast_pool_name = "_nnc_fast_pool"
            slow_pool_name = "_nnc_slow_pool"
        else:
            fast_pool_name = "_nnc_memory_pool"
            slow_pool_name = None

        # Get tensor offsets from allocation plan
        tensor_offsets = {}
        spilled_tensors = set()

        if alloc_plan is not None:
            # Use new MemoryAllocationPlan
            for tensor_name, alloc in alloc_plan.tensor_allocations.items():
                if alloc.is_spilled:
                    # Spilled tensors go to slow memory
                    tensor_offsets[tensor_name] = ("slow", alloc.offset)
                    spilled_tensors.add(tensor_name)
                else:
                    # Non-spilled tensors go to fast memory
                    # Use alloc.offset which is the tensor's offset within the buffer
                    tensor_offsets[tensor_name] = ("fast", alloc.offset)
        elif unified_plan is not None:
            # Use unified memory plan for offsets
            for buf in unified_plan.buffers:
                for tensor_name in buf.tensors:
                    tensor_offsets[tensor_name] = ("fast", buf.offset)
        elif "memory_plan" in ctx.metadata:
            # Use legacy memory plan
            from nnc_py.passes.memory_plan import get_memory_plan
            from nnc_py.passes.spill import get_spill_plan
            plan = get_memory_plan(ctx)
            spill_plan = get_spill_plan(ctx)

            if spill_plan is not None and spill_plan.has_overflow:
                # Has spill from legacy plan
                spilled_tensors = set(spill_plan.spilled_tensors)

            for tensor_name, mem_info in plan.tensor_info.items():
                pool_type = "slow" if tensor_name in spilled_tensors else "fast"
                tensor_offsets[tensor_name] = (pool_type, mem_info.pool_offset)

        # Define all non-constant tensors
        for tensor_name, tensor in ctx.graph.tensors.items():
            if tensor_name in ctx.graph.constants:
                continue

            var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
            shape_list = tensor.shape.dims
            shape_init = ", ".join(str(d) for d in shape_list)

            lines.append(f"/* Tensor: {tensor_name} */")
            lines.append(f"static int64_t {var_name}_shape[] = {{{shape_init}}};")

            # Get memory info if available
            if tensor_name in tensor_offsets:
                pool_type, offset = tensor_offsets[tensor_name]
                if pool_type == "slow":
                    pool_to_use = slow_pool_name
                else:
                    pool_to_use = fast_pool_name
                data_init = f"{pool_to_use} + {offset}" if pool_to_use else "NULL"
            else:
                # Tensor not in memory plan (e.g., constant)
                data_init = "NULL"

            # Map dtype
            dtype_enum = self._map_dtype_to_enum(tensor.dtype)

            lines.append(f"Tensor {var_name} = {{")
            lines.append(f"    .data = {data_init},")
            lines.append(f"    .dtype = {dtype_enum},")
            lines.append(f"    .shape = {var_name}_shape,")
            lines.append(f"    .ndim = {len(shape_list)},")
            lines.append(f"    .nbytes = {tensor.byte_size()},")
            lines.append("};")
            lines.append("")

        return "\n".join(lines)

    def _generate_memory_pool(self, ctx: CompileContext) -> List[str]:
        """Generate static memory pool declaration."""
        from nnc_py.passes.memory_planning import get_memory_allocation_plan
        from nnc_py.passes.memory_plan import get_memory_plan
        from nnc_py.passes.spill import get_spill_plan
        from nnc_py.passes.unified_memory import get_unified_memory_plan

        # Check for new memory allocation plan first
        alloc_plan = get_memory_allocation_plan(ctx)

        if alloc_plan is not None and (alloc_plan.has_spill or any(alloc.is_spilled for alloc in alloc_plan.tensor_allocations.values())):
            # Generate dual memory pools using new MemoryAllocationPlan
            return [
                "/* Dual Memory Pools (Fast + Slow for spilled tensors) */",
                f"/* Fast memory: {alloc_plan.total_fast_memory} bytes ({alloc_plan.total_fast_memory / 1024:.2f} KB) */",
                f"/* Slow memory: {alloc_plan.total_slow_memory} bytes ({alloc_plan.total_slow_memory / 1024:.2f} KB) */",
                f"/* Buffers: {alloc_plan.num_buffers}, Spill points: {alloc_plan.spill_count}, Reload points: {alloc_plan.reload_count} */",
                "",
                f"/* Fast Memory Pool (SRAM/On-chip) */",
                f"#define NNC_FAST_MEMORY_SIZE {alloc_plan.total_fast_memory}",
                f"#define NNC_MEMORY_ALIGNMENT 16",
                f"static uint8_t _nnc_fast_pool[NNC_FAST_MEMORY_SIZE] "
                f"__attribute__((aligned(NNC_MEMORY_ALIGNMENT))) = {{0}};",
                "",
                f"/* Slow Memory Pool (DRAM/External) */",
                f"#define NNC_SLOW_MEMORY_SIZE {alloc_plan.total_slow_memory}",
                f"uint8_t _nnc_slow_pool[NNC_SLOW_MEMORY_SIZE] "
                f"__attribute__((aligned(NNC_MEMORY_ALIGNMENT))) = {{0}};",
                "",
            ]

        # Check for unified memory plan (legacy)
        unified_plan = None
        if "unified_memory_plan" in ctx.metadata:
            try:
                unified_plan = get_unified_memory_plan(ctx)
            except RuntimeError:
                pass

        if unified_plan is not None and unified_plan.has_spill:
            # Generate dual memory pools using UnifiedMemoryPlan
            return [
                "/* Dual Memory Pools (Fast + Slow for overflow) - Using UnifiedMemoryPlan */",
                f"/* Fast memory limit: {unified_plan.fast_memory_limit} bytes ({unified_plan.fast_memory_limit / 1024:.2f} KB) */",
                f"/* Peak memory required: {unified_plan.peak_memory} bytes ({unified_plan.peak_memory / 1024:.2f} KB) */",
                f"/* Slow memory used: {unified_plan.slow_memory_size} bytes ({unified_plan.slow_memory_size / 1024:.2f} KB) */",
                f"/* Buffers: {unified_plan.buffer_count}, Spill points: {unified_plan.spill_count} */",
                "",
                f"/* Fast Memory Pool (SRAM/On-chip) */",
                f"#define NNC_FAST_MEMORY_SIZE {unified_plan.fast_memory_limit}",
                f"#define NNC_MEMORY_ALIGNMENT 16",
                f"uint8_t _nnc_fast_pool[NNC_FAST_MEMORY_SIZE] "
                f"__attribute__((aligned(NNC_MEMORY_ALIGNMENT))) = {{0}};",
                "",
                f"/* Slow Memory Pool (DRAM/External) */",
                f"#define NNC_SLOW_MEMORY_SIZE {unified_plan.slow_memory_size}",
                f"uint8_t _nnc_slow_pool[NNC_SLOW_MEMORY_SIZE] "
                f"__attribute__((aligned(NNC_MEMORY_ALIGNMENT))) = {{0}};",
                "",
            ]

        # Fall back to legacy implementation
        plan = get_memory_plan(ctx)
        spill_plan = get_spill_plan(ctx)

        # Check if we have spill (overflow)
        has_spill = spill_plan is not None and spill_plan.has_overflow

        if has_spill:
            # Generate dual memory pools
            lines = [
                "/* Dual Memory Pools (Fast + Slow for overflow) */",
                f"/* Fast memory limit: {spill_plan.max_memory} bytes ({spill_plan.max_memory / 1024:.2f} KB) */",
                f"/* Original requirement: {plan.total_size} bytes ({plan.total_size / 1024:.2f} KB) */",
                f"/* Slow memory used: {spill_plan.slow_memory_size} bytes ({spill_plan.slow_memory_size / 1024:.2f} KB) */",
                f"/* Spilled tensors: {len(spill_plan.spilled_tensors)} */",
                "",
                f"/* Fast Memory Pool (SRAM/On-chip) */",
                f"#define NNC_FAST_MEMORY_SIZE {spill_plan.max_memory}",
                f"#define NNC_MEMORY_ALIGNMENT {plan.alignment}",
                f"uint8_t _nnc_fast_pool[NNC_FAST_MEMORY_SIZE] "
                f"__attribute__((aligned(NNC_MEMORY_ALIGNMENT))) = {{0}};",
                "",
                f"/* Slow Memory Pool (DRAM/External) */",
                f"#define NNC_SLOW_MEMORY_SIZE {spill_plan.slow_memory_size}",
                f"uint8_t _nnc_slow_pool[NNC_SLOW_MEMORY_SIZE] "
                f"__attribute__((aligned(NNC_MEMORY_ALIGNMENT))) = {{0}};",
                "",
            ]
            return lines
        else:
            # Single memory pool (no overflow)
            lines = [
                "/* Static Memory Pool */",
                f"/* Total size: {plan.total_size} bytes ({plan.total_size / 1024:.2f} KB) */",
                f"/* Buffers: {plan.num_buffers}, Tensors: {plan.num_tensors} */",
                f"#define NNC_MEMORY_SIZE {plan.total_size}",
                f"#define NNC_MEMORY_ALIGNMENT {plan.alignment}",
                f"static uint8_t _nnc_memory_pool[NNC_MEMORY_SIZE] "
                f"__attribute__((aligned(NNC_MEMORY_ALIGNMENT))) = {{0}};",
                "",
            ]
            return lines

    def _map_dtype_to_enum(self, dtype: "DataType") -> str:
        """Map IR dtype to NNC dtype enum."""
        from nnc_py.ir.types import DataType

        mapping = {
            DataType.FLOAT32: "NNC_DTYPE_FLOAT32",
            DataType.FLOAT16: "NNC_DTYPE_FLOAT16",
            DataType.INT32: "NNC_DTYPE_INT32",
            DataType.INT8: "NNC_DTYPE_INT8",
            DataType.UINT8: "NNC_DTYPE_UINT8",
            DataType.BOOL: "NNC_DTYPE_BOOL",
        }
        return mapping.get(dtype, "NNC_DTYPE_FLOAT32")

    def _generate_test_runner(self, ctx: CompileContext) -> str:
        """Generate test runner."""
        # Check if memory planning was performed
        has_memory_plan = "memory_plan" in ctx.metadata

        # Generate tensor setup code
        tensor_setups = []

        if has_memory_plan:
            # Static allocation - memory is pre-allocated in memory pool
            # Only need to initialize input tensors with test data
            from nnc_py.passes.memory_plan import get_memory_plan
            plan = get_memory_plan(ctx)

            tensor_setups.append(f"    /* Using static memory pool: {plan.total_size} bytes */")
            tensor_setups.append("")

            # Setup input tensors - only initialize with test data
            for tensor_name in ctx.graph.inputs:
                tensor = ctx.graph.get_tensor(tensor_name)
                var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
                size = tensor.byte_size()

                # Get memory info
                if tensor_name in plan.tensor_info:
                    mem_info = plan.tensor_info[tensor_name]
                    tensor_setups.append(f"    /* Initialize {var_name} at offset {mem_info.pool_offset} */")
                else:
                    tensor_setups.append(f"    /* Initialize {var_name} */")

                # Initialize with test pattern
                num_elements = size // 4
                tensor_setups.append(f"    for (int i = 0; i < {num_elements}; i++) {{")
                tensor_setups.append(f"        ((float*){var_name}.data)[i] = (float)i * 0.01f;  /* Test pattern */")
                tensor_setups.append(f"    }}")
                tensor_setups.append("")
        else:
            # Dynamic allocation - use malloc/calloc
            # Setup input tensors
            for tensor_name in ctx.graph.inputs:
                tensor = ctx.graph.get_tensor(tensor_name)
                var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
                size = tensor.byte_size()

                # Generate shape array
                shape_list = tensor.shape.dims
                shape_init = ", ".join(str(d) for d in shape_list)

                # Setup code
                tensor_setups.append(f"    /* Setup {var_name} */")
                tensor_setups.append(f"    static int64_t {var_name}_shape[] = {{{shape_init}}};")
                tensor_setups.append(f"    {var_name}.shape = {var_name}_shape;")
                tensor_setups.append(f"    {var_name}.ndim = {len(shape_list)};")
                tensor_setups.append(f"    {var_name}.dtype = NNC_DTYPE_FLOAT32;")
                tensor_setups.append(f"    {var_name}.nbytes = {size};")
                tensor_setups.append(f"    {var_name}.data = malloc({size});")
                tensor_setups.append(f"    if (!{var_name}.data) {{ fprintf(stderr, \"Failed to allocate {var_name}\\\\n\"); return 1; }}")

                # Initialize with test pattern
                num_elements = size // 4
                tensor_setups.append(f"    for (int i = 0; i < {num_elements}; i++) {{")
                tensor_setups.append(f"        ((float*){var_name}.data)[i] = (float)i * 0.01f;  /* Test pattern */")
                tensor_setups.append(f"    }}")
                tensor_setups.append("")

            # Setup intermediate and output tensors
            for tensor_name, tensor in ctx.graph.tensors.items():
                if tensor_name in ctx.graph.inputs or tensor_name in ctx.graph.constants:
                    continue

                var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
                size = tensor.byte_size()
                shape_list = tensor.shape.dims
                shape_init = ", ".join(str(d) for d in shape_list)

                tensor_setups.append(f"    /* Setup {var_name} */")
                tensor_setups.append(f"    static int64_t {var_name}_shape[] = {{{shape_init}}};")
                tensor_setups.append(f"    {var_name}.shape = {var_name}_shape;")
                tensor_setups.append(f"    {var_name}.ndim = {len(shape_list)};")
                tensor_setups.append(f"    {var_name}.dtype = NNC_DTYPE_FLOAT32;")
                tensor_setups.append(f"    {var_name}.nbytes = {size};")
                tensor_setups.append(f"    {var_name}.data = calloc({size // 4}, sizeof(float));  /* Initialize to zero */")
                tensor_setups.append(f"    if (!{var_name}.data) {{ fprintf(stderr, \"Failed to allocate {var_name}\\\\n\"); return 1; }}")
                tensor_setups.append("")

        setup_code = "\n".join(tensor_setups)

        # Free memory - only for dynamic allocation
        if has_memory_plan:
            frees_code = "    /* Static allocation - no free needed */"
        else:
            tensor_frees = []
            for tensor_name in ctx.graph.tensors:
                if tensor_name in ctx.graph.constants:
                    continue
                var_name = ctx.tensor_symbols.get(tensor_name, tensor_name)
                tensor_frees.append(f"    free({var_name}.data);")
            frees_code = "\n".join(tensor_frees)

        # Get input and output tensor variable names
        input_var = None
        if ctx.graph.inputs:
            input_name = ctx.graph.inputs[0]
            input_var = ctx.tensor_symbols.get(input_name, input_name)

        output_var = None
        if ctx.graph.outputs:
            output_name = ctx.graph.outputs[0]
            output_var = ctx.tensor_symbols.get(output_name, output_name)

        # Generate print code only if we have input/output tensors
        print_code = ""
        if input_var and output_var:
            print_code = f"""
    /* Print input info */
    printf("Input data (first 10):\\n");
    int64_t input_size = 1;
    for (int i = 0; i < {input_var}.ndim; i++) {{
        input_size *= {input_var}.shape[i];
    }}
    for (int i = 0; i < 10 && i < input_size; i++) {{
        printf("  input[%d] = %f\\n", i, ((float*){input_var}.data)[i]);
    }}

    /* Run inference */
    printf("\\nRunning inference...\\n");
    nnc_run();

    /* Print output results */
    printf("\\nOutput results (first 10):\\n");
    int64_t output_size = 1;
    for (int i = 0; i < {output_var}.ndim; i++) {{
        output_size *= {output_var}.shape[i];
    }}
    for (int i = 0; i < 10 && i < output_size; i++) {{
        printf("  output[%d] = %f\\n", i, ((float*){output_var}.data)[i]);
    }}"""
        else:
            print_code = """
    /* Run inference */
    printf("Running inference...\\n");
    nnc_run();"""

        return f"""/* Auto-generated by NNC - DO NOT EDIT */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "nnc_types.h"
#include "model.h"

int main(void) {{
    printf("NNC Model Runner\\n");
    printf("================\\n");

    /* Setup all tensors */
{setup_code}
{print_code}

    /* Free memory */
{frees_code}

    printf("\\nInference complete.\\n");
    return 0;
}}
"""

    def _assign_symbols(self, ctx: CompileContext):
        """Assign C symbol names using NameManager."""
        name_manager = NameManager()

        # Assign names for tensors
        for tensor_name, tensor in ctx.graph.tensors.items():
            # Use NameManager to sanitize the name
            c_name = name_manager.get_symbol(tensor_name, prefix="tensor_")
            ctx.tensor_symbols[tensor_name] = c_name

        # Assign names for nodes
        for node_name in ctx.graph.nodes:
            c_name = name_manager.get_symbol(node_name, prefix="node_")
            ctx.node_symbols[node_name] = c_name

    def _map_dtype(self, dtype: DataType) -> str:
        """Map IR dtype to C dtype."""
        mapping = {
            DataType.FLOAT32: "float",
            DataType.FLOAT16: "uint16_t",
            DataType.INT32: "int32_t",
            DataType.INT8: "int8_t",
            DataType.UINT8: "uint8_t",
            DataType.BOOL: "uint8_t",
        }
        return mapping.get(dtype, "float")

    def _map_numpy_dtype(self, np_dtype) -> str:
        """Map numpy dtype to C dtype."""
        import numpy as np

        if np_dtype == np.float32:
            return "float"
        elif np_dtype == np.float16:
            return "uint16_t"
        elif np_dtype == np.int32:
            return "int32_t"
        elif np_dtype == np.int8:
            return "int8_t"
        elif np_dtype == np.uint8:
            return "uint8_t"
        else:
            return "float"
